import fs from 'node:fs';
import path from 'node:path';
export const spec=(kind,mode,max=10,extra={})=>({kind,mode,max,...extra});
const S=spec;
export const weeks={
1:[S('sort','colour',5),S('count','oneToOne',5),S('count','represent',5),S('match','numeral',5),S('compare','sets',5)],
2:[S('count','represent',10),S('match','numeral',10),S('line','locate',10),S('one','more',10),S('one','less',10)],
3:[S('compare','sets'),S('compare','numerals'),S('compare','language'),S('order','ascending'),S('sequence','missing')],
4:[S('bonds','missing',5),S('bonds','all',5),S('bonds','parts',10),S('bonds','missing',10),S('bonds','story',10)],
5:['combine','signs','all','on','story'].map(m=>S('add',m)),
6:['take','signs','cross','back','story'].map(m=>S('subtract',m)),
7:[S('family','addition'),S('family','inverse'),S('missing','part'),S('compareCalc','add'),S('compareCalc','subtract')],
8:[S('word','choose'),S('missing','mixed'),S('word','mixed'),S('error','mixed'),S('review','number')],
9:[S('shape','name3d'),S('shape','sort3d'),S('shape','name2d'),S('shape','sort2d'),S('pattern','shapes')],
10:[S('review','place'),S('review','compare'),S('add','story'),S('subtract','story'),S('review','number')],
11:[S('sequence','forward',20),S('tens','build',20),S('tens','represent',20),S('tens','read',20),S('compare','tens',20)],
12:[S('order','ascending',20),S('one','both',20),S('line','locate',20),S('sequence','missing',20),S('review','place',20)],
13:[S('bonds','missing',10),S('bonds','parts',20),S('add','double',20),S('add','near',20),S('add','on',20)],
14:[S('add','bridge',20),S('subtract','nocross',20),S('subtract','bridge',20),S('family','inverse',20),S('missing','mixed',20)],
15:[S('add','story',20),S('subtract','story',20),S('word','choose',20),S('error','mixed',20),S('review','number',20)],
16:[S('tens','count',50),S('tens','build',50),S('tens','represent',50),S('sequence','both',50),S('line','locate',50)],
17:[S('one','both',50),S('compare','tens',50),S('order','ascending',50),S('sequence','skip25',50),S('review','place',50)],
18:['length','units','cm','height','lengthProblem'].map(m=>S('measure',m)),
19:['mass','massUnits','full','capacity','massCapacity'].map(m=>S('measure',m)),
20:[S('review','place',20),S('review','number',20),S('review','place',50),S('review','measure'),S('review','spring',20)],
21:[S('sequence','twos',20),S('groups','equal',20),S('groups','repeated',20),S('groups','array',20),S('add','double',20)],
22:[S('sequence','skip510',50),S('groups','share',20),S('groups','group',20),S('groups','story',20),S('review','groups',20)],
23:[S('fraction','shape',10,{parts:2}),S('fraction','objects',10,{parts:2}),S('fraction','shape',10,{parts:2}),S('fraction','quantity',20,{parts:2}),S('fraction','whole',10,{parts:2})],
24:[S('fraction','shape',20,{parts:4}),S('fraction','objects',20,{parts:4}),S('fraction','quantity',20,{parts:4}),S('fraction','equal',20,{parts:4}),S('review','fractions',20)],
25:['position','ordinal','turn','direction','route'].map(m=>S('position',m)),
26:[S('sequence','both',100),S('tens','count',100),S('tens','represent',100),S('tens','read',100),S('line','locate',100)],
27:[S('one','both',100),S('compare','tens',100),S('order','ascending',100),S('sequence','skip2510',100),S('review','place',100)],
28:['coins','notes','compare','equivalent','problem'].map(m=>S('money',m)),
29:['sequence','calendar','duration','hour','half'].map(m=>S('time',m)),
30:[S('review','place',100),S('review','number',20),S('review','groupsFractions',20),S('review','measureMoneyTime'),S('review','final',20)]
};
const words=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty'];
export const numberWords=n=>n<=20?words[n]:n===100?'one hundred':['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'][Math.floor(n/10)]+(n%10?'-'+words[n%10]:'');
const shapeNames=['circle','triangle','square','rectangle'],solidNames=['cube','cuboid','sphere','cylinder','cone','square-based pyramid'];
export const profiles={
sort:{v:['sort','group','same','different','rule'],prior:'Notice one property of an object, such as its colour or shape.',steps:['Say the sorting rule before moving an object.','Look at one object and name the property being checked.','Move it into the matching group.','Check every object against the same rule and explain the groups.'],mis:'Pip changes the sorting rule halfway through. Should he keep using the same rule?',check:'Every object in a group must follow the stated sorting rule.'},
count:{v:['count','number','altogether','one for each'],prior:'Touch or move one object while saying one number word.',steps:['Choose a starting object.','Touch or move one object for each number word.','Keep the counted objects separate from those still to count.','Say the last number again because it tells how many altogether.'],mis:'Pip counts one object twice. How can he move each object so this does not happen?',check:'Each object is counted once, and the last number tells the total.'},
match:{v:['numeral','number','quantity','match'],prior:'Count a small collection using one number word for each object.',steps:['Count each object once.','Say how many objects there are altogether.','Find the numeral that represents that amount.','Move the numeral beside the collection and count again to check.'],mis:'Pip chooses the biggest-looking numeral card. Should he count the objects instead?',check:'The numeral must name the number of objects in the collection.'},
compare:{v:['more','fewer','equal','greater','less'],prior:'Count each object once and connect a set to its numeral.',steps:['Count each set or build the numerals with tens and ones.','Match equal units in the two representations.','Look for unmatched objects or the first different place value.','Say which quantity is greater, less or equal and explain the evidence.'],mis:'A longer spread-out row is not always more. Pair or count the objects to check.',check:'Moving the same objects farther apart does not change their number.'},
order:{v:['smallest','greatest','order','between'],prior:'Compare two quantities and recognise their numerals.',steps:['Build or locate each number.','Find the smallest number and move its card first.','Compare the remaining numbers and place them in order.','Read the sequence and check each neighbouring pair.'],mis:'Do not order by the last digit alone. Compare tens before ones.',check:'In ascending order, every next number is greater than the one before.'},
sequence:{v:['before','after','forwards','backwards','step'],prior:'Say a short number sequence and find the next number.',steps:['Find the starting number and direction.','Show one equal-sized jump at a time.','Count each landing number, not the starting point again.','Fill the gap and check that every step uses the same rule.'],mis:'Counting in fives means adding five each time, not saying every fifth written numeral at random.',check:'The size and direction of each step must stay the same.'},
line:{v:['number line','interval','before','after'],prior:'Order small sets of numerals.',steps:['Read the labelled endpoints and count the equal intervals.','Find the value of each interval.','Move along the line from a labelled number to the target.','Check the target against its two neighbours.'],mis:'Count the spaces between tick marks, not the number of tick marks.',check:'Equal distances on this number line represent equal differences.'},
tens:{v:['ten','ones','tens','numeral'],prior:'Count ten objects reliably and recognise a full ten frame.',steps:['Count ten ones and move them together into one group.','Keep every complete ten together and count the leftover ones.','Move the tens digit and ones digit into the place-value chart.','Say the number as tens and ones, then read the whole numeral.'],mis:'The 4 in 42 represents four tens, not four ones. Rebuild it as forty and two.',check:'One ten can be exchanged for ten ones without changing the total.'},
one:{v:['one more','one less','before','after'],prior:'Count forwards and backwards from a given number.',steps:['Represent the starting number.','Move one object in for one more, or out for one less.','Rename a full group of ten when crossing a tens boundary.','Read the new number and check it against the number sequence.'],mis:'At 29, one more is 30. Do not write 210 or restart the ones without changing the tens.',check:'One more and one less change the total by exactly one.'},
bonds:{v:['part','whole','bond','altogether'],prior:'Count a small collection and recognise that moving it does not change its total.',steps:['Count the whole collection.','Move the counters into two parts without losing any.','Count both parts and match them to a part-whole model.','Recombine the parts to check the whole. Move one counter to find a new bond.'],mis:'The whole is both parts combined. It is not just the larger part.',check:'When one part increases by one, the other decreases by one if the whole stays fixed.'},
add:{v:['add','plus','equals','total','count on'],prior:'Count objects once and find one more.',steps:['Represent the first quantity and then the quantity being added.','Move the added objects into the first set, or count on from the first number.','When crossing ten, fill the ten first and add the remaining ones.','Count the total and connect the action to the addition equation.'],mis:'When counting on, the first jump lands on the next number. Do not count the starting number as a jump.',check:'Changing the order of two addends leaves the total unchanged.'},
subtract:{v:['subtract','minus','left','take away','count back'],prior:'Count a set and identify one less.',steps:['Build the starting whole.','Move away exactly the number being subtracted.','When crossing ten, reach ten first and then subtract the remaining part.','Count what remains and use addition to check the starting whole.'],mis:'Count what remains after taking away, not the removed objects.',check:'The amount left plus the amount removed must equal the starting whole.'},
family:{v:['part','whole','related facts','inverse'],prior:'Combine two parts and take a part away from a whole.',steps:['Build two coloured parts of one whole.','Read an addition fact and swap the order of the two parts.','Start with the whole and move away one part.','Record the related subtraction and check that the same three numbers are used.'],mis:'A subtraction fact starts with the whole, not with either part.',check:'Every fact uses the same whole and the same two parts.'},
missing:{v:['missing','part','whole','equals'],prior:'Use a part-whole model and familiar number bonds.',steps:['Identify which amount is the whole and which part is known.','Build the known part and the whole.','Move counters to find the gap between them.','Replace the missing number and check the complete equation.'],mis:'An empty box does not always mean the answer comes after equals. Read the whole equation.',check:'Both sides of the equals sign must represent the same amount.'},
compareCalc:{v:['statement','equal','greater','less'],prior:'Calculate small additions and subtractions with objects.',steps:['Model the first calculation and find its total.','Model the second calculation and find its total.','Compare the two totals, not just one number in each expression.','Complete the statement using greater than, less than or equal to.'],mis:'A statement with a larger first number does not always have a larger result.',check:'Compare the results of the whole calculations.'},
word:{v:['altogether','left','more','fewer'],prior:'Act out combining and taking away with small sets.',steps:['Retell the story and identify the starting amount.','Decide whether objects join or leave.','Move the objects to act out that change.','Record the matching calculation and answer using the story unit.'],mis:'Choose the operation from what happens in the story, not from one isolated word.',check:'The numerical answer must make sense in the story.'},
error:{v:['check','explain','correct','equals'],prior:'Model addition and subtraction with objects.',steps:['Read the proposed answer without assuming it is correct.','Build the starting quantity and show the change.','Compare the model with the proposed result.','Correct the calculation and explain exactly where the count went wrong.'],mis:'A confident answer can still be wrong. Check it using the model.',check:'A useful explanation identifies the mathematical error, not just that an answer is wrong.'},
shape:{v:['shape','side','corner','flat','curved'],prior:'Notice similarities and differences in everyday objects.',steps:['Look at and, where possible, handle the shapes.','Point to the property being used, such as straight sides or flat faces.','Name or sort the shapes using that property.','Rotate a shape and check that its mathematical name has not changed.'],mis:'A square stays a square when turned. A sphere is a solid shape; a circle is flat.',check:'Changing a shape’s size or orientation does not change its defining properties.'},
pattern:{v:['repeat','unit','next','pattern'],prior:'Name and distinguish circles, triangles and squares.',steps:['Read the shapes from left to right.','Identify the smallest group that repeats.','Move a copy of that group after the existing pattern.','Predict the next shape and verify it by continuing the repeat.'],mis:'The last visible shape alone does not tell you the repeating unit.',check:'Every complete repeated group must follow the same order.'},
measure:{v:['compare','longer','shorter','heavier','capacity'],prior:'Compare two objects directly and count equal units.',steps:['Decide which property is being measured.','Line up endpoints, balance the scales, or use the same measuring cup.','Use equal units with no gaps or overlaps and count them carefully.','State the comparison with its unit and explain how the model proves it.'],mis:'An object’s size alone does not tell you its mass or capacity. Use a fair comparison.',check:'Measurements can only be compared fairly when the unit and method are consistent.'},
groups:{v:['equal','group','share','each','altogether'],prior:'Count small sets and match one object to each place.',steps:['Identify the total or the number and size of the groups.','Move objects one at a time into equal groups.','Check that every group contains the same number.','Count each group or count all the groups to answer the question.'],mis:'Equal groups have the same number of objects, even if their spacing is different.',check:'Recombining all groups must reproduce the starting total.'},
fraction:{v:['whole','equal part','half','quarter'],prior:'Share small quantities equally between two groups.',steps:['Identify the whole before dividing it.','Partition or share it into the required number of equal parts.','Select one of those equal parts.','Name the fraction and recombine all parts to check the whole.'],mis:'Two unequal pieces are not halves. Four unequal pieces are not quarters.',check:'Every part must be equal and all the parts together must make the whole.'},
position:{v:['left','right','between','turn','first'],prior:'Identify the front of an object and follow a single movement instruction.',steps:['Agree the starting place, facing direction or order.','Read one position or movement instruction at a time.','Move or turn the object so everyone can follow it.','Describe the final position and check by retracing the route.'],mis:'A turn changes facing direction; moving forwards changes position.',check:'Directions only make sense when the starting point and facing direction are clear.'},
money:{v:['coin','note','pence','pound','value'],prior:'Count in ones, twos, fives and tens.',steps:['Read the denomination on each money model.','Name the unit as pence or pounds.','Count the values rather than the number or size of coins.','Compare or combine the amounts and check with a second arrangement.'],mis:'A bigger coin is not always worth more. Read its denomination.',check:'Different collections can have the same total value.'},
time:{v:['before','after','hour','minute','half past'],prior:'Order familiar daily events and read numbers to twelve.',steps:['Identify the sequence, duration or clock being shown.','Follow the order or move the appropriate clock hand.','Read the short hand for the hour and the long hand for minutes.','Check that the spoken time or order matches both parts of the model.'],mis:'At half past, the hour hand is halfway between two hour numbers, not exactly on the first.',check:'One hour has sixty minutes; half an hour has thirty minutes.'}
};
function baseRecipe(r,v){
 if(r.kind!=='review')return r;
 const sets={place:[S('tens','build',r.max),S('compare','numerals',r.max),S('one','both',r.max),S('order','ascending',r.max),S('sequence','missing',r.max)],compare:[S('compare','sets'),S('one','both'),S('order','ascending')],number:[S('add','story',r.max),S('subtract','story',r.max),S('missing','part',r.max),S('family','inverse',r.max),S('word','mixed',r.max)],measure:[S('measure','length'),S('measure','height'),S('measure','mass'),S('measure','capacity')],spring:[S('tens','build',50),S('add','bridge',20),S('subtract','bridge',20),S('measure','cm'),S('measure','massUnits')],groups:[S('groups','share',20),S('groups','array',20),S('groups','group',20)],fractions:[S('fraction','shape',20,{parts:4}),S('fraction','objects',20,{parts:2}),S('fraction','equal',20,{parts:4})],groupsFractions:[S('groups','share',20),S('groups','array',20),S('fraction','objects',20,{parts:2}),S('fraction','quantity',20,{parts:4})],measureMoneyTime:[S('measure','cm'),S('money','equivalent'),S('time','hour'),S('time','half'),S('measure','capacity')],final:[S('tens','build',100),S('add','bridge',20),S('groups','share',20),S('fraction','quantity',20,{parts:4}),S('time','half')]};return sets[r.mode][v%sets[r.mode].length];
}
export function example(recipe,index=0,level='expected'){
 const r=baseRecipe(recipe,index),v=index%12,small=level==='lower',M=r.max??10,low=M<=10?2:M<=20?11:M<=50?21:51;
 let model={...r},q,a,answer,steps=[];
 const n=small?(M<=10?3+v%4:low+v%4):Math.min(M-1,low+v%(M<=10?7:Math.min(M-low,20)));
 const A=small?2+v%3:M<=10?3+v%4:8+v%5,B=small?1+v%2:M<=10?1+v%3:2+v%6;
 switch(r.kind){
 case 'sort':{const byShape=r.mode==='shape'||v%2===1;model={...model,mode:byShape?'shape':'colour'};q=byShape?'Sort six objects into circles and squares. Say the rule.':'Sort six objects into red and blue groups. Say the rule.';answer=byShape?'circles and squares':'red and blue';a=byShape?'Circles together and squares together. The rule is sort by shape.':'Red objects together and blue objects together. The rule is sort by colour.';break;}
 case 'count':{const amount=Math.max(0,Math.min(M,small?2+v%3:1+v%Math.max(1,M)));model={...model,n:amount,frame:r.mode==='represent'};q=r.mode==='represent'?`Count ${amount} objects and show the same amount in a frame.`:`Count the objects carefully. How many are there altogether?`;answer=String(amount);a=`${amount} altogether. Count each object once.`;break;}
 case 'match':{const amount=Math.max(0,Math.min(M,small?2+v%3:1+v%Math.max(1,M)));model={...model,n:amount};q=`Count ${amount} objects. Which numeral matches the quantity?`;answer=String(amount);a=`The numeral ${amount} matches ${amount} objects.`;break;}
 case 'compare':{const x=n,y=v%4===0?n:Math.max(0,n+(v%2?1:-2));model={...model,a:x,b:y};const word=x===y?'equal to':x>y?'greater than':'less than';q=`Compare ${x} and ${y}. Say greater than, less than or equal to.`;a=`${x} is ${word} ${y}.`;answer=word;break;}
 case 'order':{const values=[n,Math.max(0,n-2),Math.min(M,n+1)];model={...model,values};q=`Order ${values.join(', ')} from smallest to greatest.`;answer=[...values].sort((x,y)=>x-y).join(', ');a=answer+'.';break;}
 case 'sequence':{const step=r.mode==='twos'?2:r.mode==='skip25'?[2,5][v%2]:r.mode==='skip510'?[5,10][v%2]:r.mode==='skip2510'?[2,5,10][v%3]:r.mode==='both'&&v%2?-1:1;let start=step>1?step*(v%3):step<0?Math.min(M,low+5+v%8):Math.min(M-4,Math.max(0,n-2));const values=Array.from({length:5},(_,i)=>start+i*step);model={...model,values,step,missing:2};q=`Fill the gap: ${values.map((x,i)=>i===2?'__':x).join(', ')}.`;answer=String(values[2]);a=`${values[2]}. ${step>0?'Add':'Subtract'} ${Math.abs(step)} each time.`;break;}
 case 'line':{const target=M<=20?Math.min(M-1,3+v):M===50?5+5*(v%9):10+10*(v%9);model={...model,n:target,step:M<=20?1:M===50?5:10};q=`Show ${target} on a number line from 0 to ${M}.`;answer=String(target);a=`Mark ${target}, ${target/model.step} intervals after 0 when each interval is ${model.step}.`;break;}
 case 'tens':{const value=r.mode==='count'?10*(1+v%(M/10)):n;model={...model,n:value};q=r.mode==='read'?`Write ${value} in words and show its tens and ones.`:`Show ${value} as tens and ones. How many of each?`;answer=`${Math.floor(value/10)} tens and ${value%10} ones`;a=`${numberWords(value)}: ${answer}.`;break;}
 case 'one':{model={...model,n};if(r.mode==='more'){q=`Find one more than ${n}.`;answer=String(n+1);a=`One more than ${n} is ${n+1}.`;model.op=1;}else if(r.mode==='less'){q=`Find one less than ${n}.`;answer=String(n-1);a=`One less than ${n} is ${n-1}.`;model.op=-1;}else{q=`Find one less and one more than ${n}.`;answer=`${n-1}, ${n+1}`;a=`One less: ${n-1}. One more: ${n+1}.`;model.op=0;}break;}
 case 'bonds':{const total=small?Math.min(5,M):M,part=1+v%(total-1);model={...model,total,part};q=r.mode==='all'?`Find every two-part bond to ${total}. Include zero.`:r.mode==='story'?`${total} birds are in a tree. ${part} are on one branch. How many are on the other?`:`The whole is ${total}. One part is ${part}. Find the missing part.`;answer=r.mode==='all'?Array.from({length:total+1},(_,i)=>`${i}+${total-i}`).join(', '):String(total-part);a=r.mode==='all'?answer+'.':`${total-part}; ${part} + ${total-part} = ${total}.`;break;}
 case 'add':case 'subtract':case 'family':case 'missing':case 'word':case 'error':case 'compareCalc':{
 let x=A,y=Math.min(B,M-A),op=r.kind==='subtract'||r.kind==='compareCalc'&&r.mode==='subtract'?'−':'+';
 if(['word','error','missing'].includes(r.kind)&&v%2)op='−';
 if(r.kind==='add'&&['double','near'].includes(r.mode)){x=2+v%7;y=x+(r.mode==='near'?1:0);}
 if(r.mode==='bridge'){if(op==='+'){x=7+v%3;y=4+v%4;}else{x=12+v%5;y=x-10+1+v%3;}}
 else if(op==='−'){x=M<=10?5+v%5:12+v%7;y=1+v%Math.min(5,x);if(r.mode==='nocross')y=Math.min(y,x-10);}
 const total=op==='+'?x+y:x-y;model={...model,a:x,b:y,op,total};answer=String(total);q=`${x} ${op} ${y} = ?`;a=`${x} ${op} ${y} = ${total}.`;
 if(r.mode==='story'||r.kind==='word'){q=op==='+'?`${x} birds sit on a fence. ${y} more join them. How many birds now?`:`${x} birds sit on a fence. ${y} fly away. How many birds remain?`;a=`${total} birds; ${x} ${op} ${y} = ${total}.`;}
 if(r.kind==='family'){model.op='+';model.total=x+y;const whole=x+y;q=`Use ${x}, ${y} and ${whole} to make related addition and subtraction facts.`;answer=`${x}+${y}=${whole}; ${y}+${x}=${whole}; ${whole}−${x}=${y}; ${whole}−${y}=${x}`;a=answer+'.';}
 if(r.kind==='missing'){q=`Fill the box: ${x} ${op} __ = ${total}.`;answer=String(y);a=`${y}; ${x} ${op} ${y} = ${total}.`;}
 if(r.kind==='error'){model.wrong=total+1;q=`Sam says ${x} ${op} ${y} = ${total+1}. Check and correct Sam.`;a=`Sam is incorrect. ${x} ${op} ${y} = ${total}. Show the objects joining or leaving.`;}
 if(r.kind==='compareCalc'){const c=op==='+'?x+1:x-1,d=y;model.c=c;model.d=d;model.other=op==='+'?c+d:c-d;q=`Compare ${x} ${op} ${y} and ${c} ${op} ${d}. Which result is greater?`;answer=String(Math.max(total,model.other));a=`${total} and ${model.other}. ${Math.max(total,model.other)} is greater.`;}
 break;}
 case 'shape':{const solid=r.mode.endsWith('3d'),names=solid?solidNames:shapeNames,name=names[v%names.length];model={...model,name,solid};const properties={circle:'a curved boundary and no straight sides',triangle:'three straight sides and three corners',square:'four equal straight sides and four square corners',rectangle:'four straight sides and four square corners',cube:'six square flat faces',cuboid:'six rectangular flat faces',sphere:'one curved surface and no flat faces',cylinder:'two circular flat faces and a curved surface',cone:'one circular flat face and a curved surface','square-based pyramid':'one square base and four triangular faces'};q=`Which shape has ${properties[name]}? Name it and show the feature.`;answer=name;a=`${name[0].toUpperCase()+name.slice(1)}. ${properties[name]}.`;if(name==='rectangle')a+=' A square is a special rectangle.';break;}
 case 'pattern':{const unit=v%2?['circle','circle','triangle']:['square','triangle'];model={...model,unit};q=`Continue the pattern with two shapes: ${[...unit,...unit].join(', ')}, __, __.`;answer=[unit[0],unit[1%unit.length]].join(', ');a=answer+'. The repeated group is '+unit.join(', ')+'.';break;}
 case 'measure':{const x=3+v%5,y=2+(v+2)%5;model={...model,a:x,b:y};const mode=r.mode==='massCapacity'?(v%2?'massUnits':'capacity'):r.mode;
 model.mode=mode;
 if(['length','height'].includes(mode)){q=`A ${mode==='height'?'tower':'ribbon'} is ${x} cubes ${mode==='height'?'tall':'long'}. Another is ${y} cubes. Compare them.`;answer=x===y?'equal':`${Math.max(x,y)} cubes`;a=x===y?'They are equal.':`The ${Math.max(x,y)}-cube ${mode==='height'?'tower is taller':'ribbon is longer'} by ${Math.abs(x-y)} cubes.`;}
 else if(['units','cm'].includes(mode)){q=`A strip covers ${x} equal ${mode==='cm'?'centimetre spaces':'cubes'} with no gaps. What is its length?`;answer=`${x} ${mode==='cm'?'cm':'cubes'}`;a=answer+'. Start measuring at zero.';}
 else if(mode==='lengthProblem'){q=`A ribbon is ${x} cm long. Another is ${y} cm longer. Find the second length.`;answer=`${x+y} cm`;a=`${x+y} cm; ${x} + ${y} = ${x+y}.`;}
 else if(mode==='mass'){q=`One bag balances ${x} identical cubes. Another balances ${y}. Which bag is heavier?`;answer=x===y?'same mass':`${Math.max(x,y)} cubes`;a=x===y?'The bags have the same mass.':`The bag that balances ${Math.max(x,y)} cubes is heavier.`;}
 else if(mode==='massUnits'){q=`A bag balances ${x} identical cubes. What is its mass in cube units?`;answer=`${x} cube units`;a=answer+'. The balance is level.';}
 else if(mode==='full'){model.fill=[0,.5,1][v%3];q=`A container holds ${model.fill===0?'no water':model.fill===1?'all the water it can hold':'half the water it can hold'}. Is it empty, half full or full?`;answer=model.fill===0?'empty':model.fill===1?'full':'half full';a=answer+'.';}
 else{q=`Container A holds ${x} equal cupfuls. B holds ${y}. Which has greater capacity?`;answer=x===y?'equal capacity':x>y?'A':'B';a=x===y?'They have equal capacity.':`${answer}, because ${Math.max(x,y)} cupfuls is more than ${Math.min(x,y)}.`;}
 break;}
 case 'groups':{const groups=2+v%3,size=2+(v+1)%3,total=groups*size;model={...model,groups,size,total};const share=r.mode==='share'||r.mode==='story'&&v%2===0,group=r.mode==='group'||r.mode==='story'&&v%2===1;q=share?`Share ${total} counters equally between ${groups} children. How many each?`:group?`Put ${total} counters in groups of ${size}. How many groups?`:`There are ${groups} equal groups of ${size}. How many counters altogether?`;answer=String(share?size:group?groups:total);a=share?`${size} each; ${groups} groups of ${size} make ${total}.`:group?`${groups} groups; ${groups} groups of ${size} make ${total}.`:`${Array(groups).fill(size).join(' + ')} = ${total}.`;break;}
 case 'fraction':{const parts=r.parts??2,total=parts*(2+v%(parts===4?4:5));model={...model,parts,total};const name=parts===2?'half':'quarter';if(r.mode==='equal'){model.equal=v%2===0;q=`A shape is split into ${parts} ${model.equal?'equal':'unequal'} parts. Is each part a ${name}? Explain.`;answer=model.equal?'yes':'no';a=model.equal?`Yes. The ${parts} parts are equal and make the whole.`:`No. A ${name} must be one of ${parts} equal parts.`;}
 else if(r.mode==='shape'){q=`Show one ${name} of a rectangle. How many equal parts make the whole?`;answer=String(parts);a=`${parts} equal parts. Shade one of them.`;}
 else if(r.mode==='whole'){q=`Two equal halves each contain ${total/2} counters. How many counters make the whole?`;answer=String(total);a=`${total}; ${total/2} + ${total/2} = ${total}.`;}
 else {q=`Find one ${name} of ${total} counters.`;answer=String(total/parts);a=`${total/parts}. Share ${total} equally into ${parts} groups and select one group.`;}break;}
 case 'position':{if(r.mode==='ordinal'){const pos=1+v%5;model={...model,pos};q=`Five children stand in a line. Count from the left. Which place is child ${pos} in?`;answer=['first','second','third','fourth','fifth'][pos-1];a=answer+'. The leftmost child is first.';}
 else if(r.mode==='turn'){const turns=[.25,.5,.75,1],turn=turns[v%4];model={...model,turn};q=`An arrow points up. Turn it ${['a quarter','a half','three quarters','a whole'][v%4]} turn clockwise. Where does it point?`;answer=['right','down','left','up'][v%4];a=answer+'.';}
 else if(r.mode==='route'||r.mode==='direction'){const dx=1+v%3,dy=1+(v+1)%2;model={...model,dx,dy};q=`Start at the bottom-left square. Move ${dx} squares right, then ${dy} up. Describe the finish.`;answer=`column ${dx+1}, row ${dy+1} from the bottom`;a=answer+'.';}
 else{const pos=['inside','above','below','left of','right of'][v%5];model={...model,position:pos};q=`Place a counter ${pos} a box. Describe where it is.`;answer=pos;a=`The counter must be ${pos} the box.`;}break;}
 case 'money':{const coins=[1,2,5,10,20,50,100,200],notes=[5,10,20,50],coin=coins[v%8];if(r.mode==='coins'){model={...model,value:coin};q=`Name the coin labelled ${coin>=100?'£'+coin/100:coin+'p'}. What is its value?`;answer=coin>=100?`${coin/100} pound${coin===100?'':'s'}`:`${coin} pence`;a=answer+'.';}
 else if(r.mode==='notes'){const value=notes[v%4];model={...model,value};q=`A banknote is labelled £${value}. What is its value?`;answer=`${value} pounds`;a=answer+'. Read the number and pound symbol.';}
 else if(r.mode==='compare'){const c=[2,5,10,20,50][v%5],d=[1,2,5,10,20][v%5];model={...model,coins:[c,d]};q=`Which is worth more: a ${c}p coin or a ${d}p coin?`;answer=`${c}p`;a=`${c}p is greater than ${d}p.`;}
 else if(r.mode==='equivalent'){const total=[5,10,20][v%3];model={...model,total,coins:total===5?[2,2,1]:total===10?[5,5]:[10,10]};q=`Make ${total}p in two different ways using coins.`;answer=`${total}p`;a=`For example: ${total}p; or ${model.coins.map(n=>n+'p').join(' + ')}. Other correct totals are valid.`;}
 else{const price=2+v%7,pay=10;model={...model,price,pay};q=`A pencil costs ${price}p. Pay 10p. How much change?`;answer=`${pay-price}p`;a=`${pay-price}p; ${price} + ${pay-price} = 10.`;}break;}
 case 'time':{if(r.mode==='hour'||r.mode==='half'){const hour=1+v%12,minute=r.mode==='half'?30:0;model={...model,hour,minute};q=`Show ${minute?'half past '+numberWords(hour):numberWords(hour)+" o’clock"} on a clock.`;answer=minute?`${hour}:30`:`${hour}:00`;a=minute?`Minute hand on 6; hour hand halfway between ${hour} and ${hour%12+1}.`:`Minute hand on 12; hour hand on ${hour}.`;}
 else if(r.mode==='calendar'){const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],months=['January','February','March','April','May','June','July','August','September','October','November','December'];const list=v%2?months:days,at=v%(list.length-1);model={...model,values:list.slice(at,at+3),answer:list[at+1]};q=`Which ${v%2?'month':'day'} comes after ${list[at]}?`;answer=list[at+1];a=answer+'.';}
 else if(r.mode==='duration'){const x=5+v%6,y=x+3;model={...model,a:x,b:y};q=`One activity takes ${x} minutes. Another takes ${y}. Which is quicker?`;answer=`${x} minutes`;a=`The ${x}-minute activity is quicker by ${y-x} minutes.`;}
 else{const values=v%2?['wake up','eat breakfast','go to school']:['eat lunch','play outside','eat dinner'];model={...model,values};q=`Put these events in a sensible order: ${[values[2],values[0],values[1]].join(', ')}.`;answer=values.join(', ');a=answer+'. Accept another order if the child gives a sensible context.';}break;}
 default:throw new Error('Missing example '+r.kind);
 }
 if(r.kind==='shape'&&r.mode.startsWith('sort')){const solid=r.mode.endsWith('3d');const names=solid?['cube','sphere','cylinder']:['circle','triangle','rectangle'];model={...model,sort:true,names};q=solid?'Sort cube, sphere and cylinder into shapes with a curved surface and shapes with only flat faces.':'Sort circle, triangle and rectangle into shapes with straight sides and shapes with no straight sides.';answer=solid?'Curved: sphere, cylinder. Only flat: cube.':'Straight sides: triangle, rectangle. No straight sides: circle.';a=answer;}
 const profile=profiles[r.kind];
 if(!q||!a||!profile)throw new Error('Incomplete '+r.kind);
 return {q,a,answer,model,steps:profile.steps,profile};
}
export function challenge(recipe,i){const e=example(recipe,i+3);const p=e.profile;
 if(i===0)return {...e,q:e.q+' Explain how your model proves it.',a:e.a+' Check that the model matches every quantity in the question.'};
 if(i===1)return {...e,q:e.q+' Show a second way to check.',a:e.a+' Accept a matching object model, number line, related fact or correctly labelled drawing.'};
 if(i===2)return {...e,q:'Is this always true? '+p.check+' Give an example.',a:'Yes, under the stated conditions. Accept a correct example that illustrates the rule.',model:null};
 if(i===3)return {...e,q:e.q+' Explain a mistake someone might make.',a:e.a+' A possible mistake: '+p.mis};
 return {...e,q:e.q+' Create a similar question for a partner and give its answer.',a:e.a+' The new question and its answer must match the same mathematical idea.'};
}
export function makeLesson(week,day,title,term){const recipe=weeks[week][day-1],examples=Array.from({length:5},(_,i)=>example(recipe,i));const p=examples[0].profile;
 const clean=title.replace(/\b(Autumn|Spring|Summer)\s*/g,'');
 return {year:1,week,day,term,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title:clean,objective:/assessment|check|reflection/i.test(clean)?'To apply the taught ideas independently, explain a method and identify a next step.':'To '+clean[0].toLowerCase()+clean.slice(1)+'.',recipe,vocabulary:p.v,successCriteria:['I can '+clean[0].toLowerCase()+clean.slice(1)+'.','I can show the idea using a mathematical model.','I can explain and check my answer.'],prior:p.prior,resources:'Teaching PowerPoint, counters, cubes, numeral cards, paper and topic equipment described in the plan.',misconception:p.mis,check:p.check,warmup:p.prior+' Use the pre-teach checks to decide whether to revisit it.',teacherModel:p.steps,guided:examples[1].q+' Ask pupils to choose each next step before advancing the animation.',independent:'Use the You do example first. Choose supported, expected or greater-depth practice according to current understanding.',plenary:examples[4].q+' Ask pupils to explain their representation and identify a next step.',preteach:{focus:p.prior,steps:p.steps.slice(0,3),questions:Array.from({length:3},(_,i)=>example(recipe,i,'lower')).map(({q,a,model})=>({q,a,model}))},lower:Array.from({length:5},(_,i)=>example(recipe,i+5,'lower')).map(({q,a,model})=>({q,a,model})),expected:Array.from({length:5},(_,i)=>example(recipe,i+5)).map(({q,a,model})=>({q,a,model})),higher:Array.from({length:5},(_,i)=>challenge(recipe,i)).map(({q,a,model})=>({q,a,model})),examples:examples.map(({q,a,answer,model})=>({q,a,answer,model}))};}
if(process.argv[1]&&path.basename(process.argv[1])==='year1_complete_content.mjs'){
const out=path.resolve(process.argv[2]??'../.qa/year1-complete'),selection=(process.argv[3]??'from-week-3').toLowerCase();fs.mkdirSync(out,{recursive:true});const plan=JSON.parse(fs.readFileSync('lessons/year-1-maths/year1-maths-plan.json','utf8'));const chosen=selection==='autumn'?plan.filter(w=>w.term==='Autumn'):selection==='all'?plan:plan.filter(w=>w.week>=3);const lessons=chosen.flatMap(w=>{const file=`lessons/year-1-maths/week-${w.week}/week${w.week}-lessons.json`,existing=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):[];return w.days.map((t,i)=>{const made=makeLesson(w.week,i+1,t,w.term),saved=existing.find(x=>x.day===i+1||x.slug===made.slug);if(saved)for(const key of ['objective','vocabulary','successCriteria','prior','resources','misconception','warmup','teacherModel','guided','independent','plenary','expected'])if(saved[key])made[key]=saved[key];return made;});});fs.writeFileSync(path.join(out,'lessons.json'),JSON.stringify(lessons,null,2));console.log('Prepared '+lessons.length+' lesson specifications');
}
