import fs from 'node:fs/promises';
import {numberWords} from './year1_complete_content.mjs';
export const source='https://www.gov.uk/government/publications/national-curriculum-in-england-mathematics-programmes-of-study/national-curriculum-in-england-mathematics-programmes-of-study#year-3-programme-of-study';
const weeks=[
['Place value to 1000','Hundreds tens and ones|Read and write three-digit numbers|Flexible partitioning|Ten more and ten less|One hundred more and less','place|words|flexible|ten|hundred'],
['Compare and represent numbers','Compare three-digit numbers|Order numbers to 1000|Numbers on a scale|Count in fifties|Count in hundreds','compare|order|numberline|fifties|hundreds'],
['Mental addition and subtraction','Add ones to three-digit numbers|Subtract ones mentally|Add and subtract tens|Add and subtract hundreds|Bridge a hundred mentally','mentalAdd|mentalSub|mentalTens|mentalHundreds|bridge'],
['Column addition','Add without exchanging|Exchange ten ones|Exchange ten tens|Add with two exchanges|Addition word problems','add|addOnes|addTens|addBoth|addStory'],
['Column subtraction','Subtract without exchanging|Exchange a ten|Exchange a hundred|Subtract across a zero|Subtraction word problems','sub|subOnes|subTens|subZero|subStory'],
['Estimate check and find missing numbers','Estimate a total|Check addition with subtraction|Check subtraction with addition|Missing numbers in addition|Missing numbers in subtraction','estimate|inverseAdd|inverseSub|missingAdd|missingSub'],
['Three four and eight times tables','Three times table|Four times table|Eight times table|Double from four to eight|Related division facts','times3|times4|times8|double48|divisionFacts'],
['Multiply two digits by one digit','Partition to multiply|Multiply without exchanging|Multiply with an exchange|Multiply tens|Multiplication word problems','partitionMultiply|multiply|multiplyExchange|multiplyTens|multiplyStory'],
['Division sharing and grouping','Share equally|Group and divide|Divide two-digit numbers|Division with remainders|Interpret a remainder','share|group|divide|remainder|remainderStory'],
['Autumn consolidation','Place value problems|Addition and subtraction problems|Multiplication and division problems|Find and explain mistakes|Autumn review','reviewPlace|reviewCalc|reviewMult|mistake|autumn'],
['Money and change','Pounds and pence|Add amounts of money|Subtract amounts of money|Find change|Two-step money problems','moneyRead|moneyAdd|moneySub|change|moneyProblem'],
['Length and perimeter','Measure in millimetres|Metres and centimetres|Compare and calculate lengths|Measure a perimeter|Find a missing side','millimetres|lengthConvert|lengthCalc|perimeter|missingSide'],
['Mass and capacity','Read mass scales|Kilograms and grams|Read capacity scales|Litres and millilitres|Add and subtract measures','massScale|massConvert|capacityScale|capacityConvert|measureCalc'],
['Unit and non-unit fractions','Equal parts and unit fractions|Non-unit fractions|Unit fractions of sets|Non-unit fractions of sets|Fractions of lengths','unitFraction|nonUnit|unitOf|fractionOf|fractionLength'],
['Tenths and fraction number lines','Make tenths|Count forwards in tenths|Count backwards in tenths|Fractions on a number line|Fractions beyond one whole','tenths|tenthsUp|tenthsDown|fractionLine|beyondWhole'],
['Equivalent fractions','Halves and quarters|Thirds and sixths|Quarters and eighths|Match equivalent fractions|Explain equivalent fractions','equiv2|equiv3|equiv4|equivMixed|equivExplain'],
['Add and subtract fractions','Add fractions within one whole|Subtract fractions|Complete the whole|Missing fraction addition|Fraction word problems','fractionAdd|fractionSub|fractionWhole|fractionMissing|fractionStory'],
['Compare and order fractions','Compare unit fractions|Order unit fractions|Compare equal denominators|Order equal denominators|Explain fraction comparisons','unitCompare|unitOrder|fractionCompare|fractionOrder|fractionReason'],
['Fraction problems','Find a fraction of a collection|Find the original whole|Fractions in measure problems|Combine fraction parts|Choose a fraction strategy','fractionOf|fractionReverse|fractionLength|fractionStory|fractionReview'],
['Spring consolidation','Money review|Length and perimeter review|Mass and capacity review|Fraction review|Spring review','moneyReview|lengthReview|measureReview|fractionReview|spring'],
['Time and calendars','Read time to the minute|Roman numeral clocks|Twelve and twenty-four hour times|Seconds minutes and durations|Months years and leap years','timeMinute|timeRoman|time24|duration|calendar'],
['Angles and turns','Recognise right angles|Angles smaller than a right angle|Angles greater than a right angle|Right angles and turns|Compare angles in shapes','rightAngle|acute|obtuse|turns|angleSort'],
['Two-dimensional and three-dimensional shapes','Draw shapes on a grid|Describe three-dimensional shapes|Recognise solids in different orientations|Make solid models|Sort shapes by properties','drawShape|solid|rotatedSolid|makeSolid|sortShape'],
['Lines and shape properties','Horizontal and vertical lines|Parallel lines|Perpendicular lines|Find lines in shapes|Draw shapes with line clues','horizontal|parallel|perpendicular|linesShape|drawLines'],
['Tables pictograms and bar charts','Read a scaled pictogram|Read a scaled bar chart|Complete a bar chart|Read and compare a table|Two-step data questions','pictogram|bar|drawBar|table|dataTwo'],
['Measure and time problems','Calculate a duration|Compare event times|Measure and draw accurately|Compare mixed units|Solve a measure problem','durationClock|timeCompare|drawMeasure|mixedUnits|measureStory'],
['Multiplication and division problems','Scale a quantity|Scale a length|Find all outfit combinations|Missing multiplication numbers|Choose multiplication or division','scale|scaleLength|correspondence|missingMult|multReview'],
['Number reasoning','Two-step addition and subtraction|Solve a missing number puzzle|Choose an efficient calculation|Explain a number statement|Solve a practical number problem','twoStep|missingReview|efficient|numberReason|numberStory'],
['Shape and data investigations','Draw different quadrilaterals|Investigate a perimeter|Organise a data table|Compare groups using data|Explain a shape and data problem','quadrilateral|perimeterInvestigate|table|dataTwo|investigate'],
['Summer consolidation','Number and calculation review|Fractions and measures review|Time and geometry review|Statistics review|Ready for Year Four','autumn|spring|summerGeometry|dataReview|final']
];
const groups={place:['hundreds','tens','ones','digit','partition'],calc:['sum','difference','exchange','inverse'],multiply:['groups','multiply','product','partition'],divide:['share','group','quotient','remainder'],fraction:['whole','numerator','denominator','equal parts'],measure:['unit','interval','length','mass','capacity'],money:['pounds','pence','cost','change'],time:['hour','minute','second','duration','am','pm','noon','midnight'],shape:['face','edge','vertex','right angle'],data:['category','scale','key','total']};
const guidance={
place:['Build the number with hundreds, tens and ones.','Name the value represented by each digit.','Move or exchange the parts while keeping their values.','Read the number and check the representation.'],
calc:['Represent both quantities and choose the operation.','Align hundreds, tens and ones or partition for a mental method.','Show each calculation and any exchange before writing the result.','Check with the inverse operation and a sensible estimate.'],
multiply:['Build equal groups or partition the two-digit factor.','Multiply each part by the same number.','Combine the partial products, exchanging if needed.','Check by repeated addition or division.'],
divide:['Identify the whole, the group size and the number of groups.','Share or group equally, moving the objects.','Record the complete groups and any remainder.','Check: divisor times quotient plus remainder equals the whole.'],
fraction:['Identify the whole before naming the fraction.','Partition into equal parts using the denominator.','Select, combine or compare the number of parts named by the numerator.','Check the diagram still represents the same whole.'],
measure:['Choose the correct measuring tool and unit.','Find the value of each interval, counting spaces rather than marks.','Read, compare or calculate with quantities in the same unit.','Record the unit and check the answer with the diagram.'],
money:['Read pounds and pence separately.','Exchange each pound for 100 pence when calculating.','Add costs or subtract to find the change.','Check that cost and change make the amount paid.'],
time:['Identify the hour hand, minute hand and clock scale.','Read the hour and count the minutes accurately.','Use jumps through the next hour to compare durations.','Check the units and whether the time is morning or afternoon.'],
shape:['Look at the shape in its actual orientation.','Trace sides, faces or lines and mark the right angles.','Use a ruler, right-angle corner or model to test the property.','Explain using shape properties rather than appearance.'],
data:['Read the title, categories and scale or key.','Work out the value represented by each interval or symbol.','Read the values and choose how to combine or compare them.','Check the calculation against the original data.']};
const prior={place:'Count in tens and recognise the value of a two-digit number.',calc:'Recall bonds to ten and partition two-digit numbers.',multiply:'Build equal groups and recall the 2, 5 and 10 times tables.',divide:'Connect equal groups with multiplication.',fraction:'Share a whole into equal halves, thirds and quarters.',measure:'Read equal intervals and name common units.',money:'Recognise UK coins and recall 100 pence makes one pound.',time:'Read o’clock, half past and five-minute times.',shape:'Name familiar flat and solid shapes.',data:'Read a simple table and a pictogram key.'};
const mis={place:'A pupil says the 4 in 407 is worth four. Show why the position matters.',calc:'A pupil exchanges a ten but forgets to reduce the tens column. Show what must change.',multiply:'A pupil multiplies only the ones digit. Show what happens to the tens.',divide:'A pupil leaves a remainder greater than the divisor. Can another group be made?',fraction:'A pupil changes the denominator when adding equal-sized parts. Explain the error.',measure:'A pupil counts scale marks instead of intervals. Show the difference.',money:'A pupil says one pound is ten pence. Use coins to correct the exchange.',time:'A pupil reads the hour from the nearest numeral. Explain how the short hand moves.',shape:'A pupil says a rotated square has changed its properties. Test that claim.',data:'A pupil counts symbols without using the key. Show the correct total.'};
const reviews={reviewPlace:['place','flexible','compare','numberline','fifties'],reviewCalc:['addBoth','subZero','missingAdd','mentalTens','inverseSub'],reviewMult:['times3','times4','times8','multiplyExchange','divide'],mistake:['inverseAdd','inverseSub','double48','equivExplain','numberReason'],autumn:['place','addBoth','subOnes','multiplyExchange','remainder'],moneyReview:['moneyRead','moneyAdd','moneySub','change','moneyProblem'],lengthReview:['millimetres','lengthConvert','lengthCalc','perimeter','missingSide'],measureReview:['massScale','capacityScale','massConvert','capacityConvert','measureCalc'],fractionReview:['unitOf','fractionOf','equiv3','fractionAdd','unitCompare'],spring:['moneyProblem','perimeter','massScale','fractionOf','fractionSub'],multReview:['multiplyStory','share','scale','correspondence','missingMult'],missingReview:['missingAdd','missingSub','missingMult','fractionMissing','fractionReverse'],summerGeometry:['timeMinute','durationClock','rightAngle','parallel','solid'],dataReview:['pictogram','bar','drawBar','table','dataTwo'],final:['twoStep','fractionOf','durationClock','linesShape','dataTwo'],investigate:['drawShape','perimeter','parallel','bar','dataTwo']};
const money=n=>`${Math.floor(n/100)} pounds ${n%100} pence`;
export function question(mode,index,level='expected'){
 const i=index%10,low=level==='lower';if(reviews[mode])return question(reviews[mode][i%5],index,level);
 let q,a,kind='place',m={},steps=[];const n=(low?100:300)+i*31+24,b=12+i*3;
 if(['place','words','flexible','ten','hundred','compare','order','numberline','fifties','hundreds'].includes(mode)){
  m={type:'place',n};q=`Partition ${n} into hundreds, tens and ones.`;a=`${Math.floor(n/100)} hundreds, ${Math.floor(n/10)%10} tens and ${n%10} ones.`;
  if(mode==='words'){q=`Write ${n} in words.`;a=numberWords(Math.floor(n/100))+' hundred and '+numberWords(n%100)+'.';}
  if(mode==='flexible'){q=`Complete: ${n} = ${Math.floor(n/100)-1} hundreds + ___ tens + ${n%10} ones.`;a=`${Math.floor(n/10)%10+10} tens.`;}
  if(['ten','hundred'].includes(mode)){const d=mode==='ten'?10:100;q=`Find ${d} more and ${d} less than ${n}.`;a=`${n+d} and ${n-d}.`;m={type:'moreLess',values:[n-d,n,n+d],delta:d};}
  if(mode==='compare'||mode==='order'){const values=[n+20,n-7,n+2];m={type:'numbers',values};q=mode==='order'?`Order ${values.join(', ')} from smallest.`:`Write <, > or =: ${n+20} ___ ${n-7}.`;a=mode==='order'?[...values].sort((a,b)=>a-b).join(', ')+'.':'>.';}
  if(mode==='numberline'){const start=Math.floor(n/100)*100,val=start+(i%9+1)*10;m={type:'numberline',start,end:start+100,value:val,step:10};q='Read the number at the marked point.';a=val+'.';}
  if(mode==='fifties'||mode==='hundreds'){const step=mode==='fifties'?50:100,start=(i%4)*step; m={type:'sequence',values:Array.from({length:5},(_,j)=>start+j*step),missing:2};q=`Fill the gap: ${m.values.map((v,j)=>j===2?'___':v).join(', ')}.`;a=m.values[2]+'.';}
 }
 else if(['mentalAdd','mentalSub','mentalTens','mentalHundreds','bridge','add','addOnes','addTens','addBoth','addStory','sub','subOnes','subTens','subZero','subStory','estimate','inverseAdd','inverseSub','missingAdd','missingSub','twoStep','efficient','numberReason','numberStory'].includes(mode)){
  kind='calc';let x=n,y=b,op=mode.startsWith('sub')||mode==='mentalSub'||mode==='missingSub'||mode==='inverseSub'?'−':'+';
  if(mode==='mentalAdd'||mode==='mentalSub')y=3+i%6;
  if(mode==='mentalTens')y=(i%5+1)*10;
  if(mode==='mentalHundreds')y=100+(i%2)*100;
  if(mode==='bridge'){x=280+i*10;y=35;}
  if(mode==='add'){x=211+i*10;y=122;}
  if(mode==='addOnes'){x=216+(i%3)*100+(i%3)*10;y=127;}
  if(mode==='addTens'){x=261+(i%3)*100;y=172;}
  if(mode==='addBoth'||mode==='addStory'){x=267+(i%3)*100;y=178;}
  if(mode==='sub'){x=456+i*10;y=123;}
  if(mode==='subOnes'){x=452+(i%3)*100+(i%2)*10;y=127;}
  if(mode==='subTens'){x=432+i*2;y=170;}
  if(mode==='subZero'){x=400+(i%4)*100;y=126;}
  if(low&&['addBoth','addStory','subStory'].includes(mode)){x=123+i*10;y=24;}
  m={type:'calculation',a:x,b:y,op,total:op==='+'?x+y:x-y};q=`Calculate ${x} ${op} ${y}.`;a=`${m.total}.`;
  if(mode==='addStory'){q=`A library has ${x} books and gets ${y} more. How many now?`;a+=` ${x} + ${y} = ${m.total}.`;}
  if(mode==='subStory'){q=`There are ${x} tickets. ${y} are sold. How many remain?`;a+=` ${x} − ${y} = ${m.total}.`;}
  if(mode==='estimate'){const r=v=>Math.round(v/100)*100;q=`Estimate ${x} + ${y} using the nearest hundred.`;a=`About ${r(x)+r(y)}. ${r(x)} + ${r(y)}.`;m={type:'estimate',a:x,b:y,total:r(x)+r(y)};}
  if(mode==='inverseAdd'){q=`Check ${x} + ${y} = ${x+y} using subtraction.`;a=`${x+y} − ${y} = ${x}.`;}
  if(mode==='inverseSub'){q=`Check ${x} − ${y} = ${x-y} using addition.`;a=`${x-y} + ${y} = ${x}.`;}
  if(mode==='missingAdd'){q=`${x} + ___ = ${x+y}.`;a=`${y}.`;}
  if(mode==='missingSub'){q=`${x} − ___ = ${x-y}.`;a=`${y}.`;}
  if(['twoStep','numberStory'].includes(mode)){const c=20+i;q=`A bus carries ${x} people over a day. ${y} more travel next day and ${c} fewer the third day than the second. How many travel on the third day?`;q=`A shop has ${x} pencils. It gets ${y} more, then sells ${c}. How many remain?`;m={type:'twoStep',a:x,b:y,c,total:x+y-c};a=`${x+y-c}. First ${x}+${y}=${x+y}, then subtract ${c}.`;}
  if(mode==='efficient'){x=199+i*100;y=24+i;m={type:'compensate',a:x,b:y,total:x+y};q=`Find ${x} + ${y} by adding ${x+1}, then adjusting.`;a=`${x+y}. Add ${x+1}, then subtract 1.`;}
  if(mode==='numberReason'){q=`Is ${n} + 10 the same as ${n+10}? Explain using place value.`;a=`Yes. Adding one ten gives ${n+10}.`;m={type:'calculation',a:n,b:10,op:'+',total:n+10};}
 }
 else if(['times3','times4','times8','double48','partitionMultiply','multiply','multiplyExchange','multiplyTens','multiplyStory','divisionFacts','share','group','divide','remainder','remainderStory','scale','scaleLength','correspondence','missingMult'].includes(mode)){
  kind=['divisionFacts','share','group','divide','remainder','remainderStory'].includes(mode)?'divide':'multiply';let x=low?2+i%5:3+i%10,y=mode==='times3'?3:mode==='times8'?8:4;
  if(['partitionMultiply','multiply','multiplyExchange','multiplyStory'].includes(mode)){x=(low?12:23)+i;y=3+i%2;}
  if(mode==='multiply'){x=21+(i%3)*10;y=2;}
  if(mode==='multiplyExchange'){x=24+i%5;y=3+i%2;}
  if(mode==='divisionFacts')y=[3,4,8][i%3];
  if(mode==='multiplyTens'){x=(2+i%7)*10;y=3;}
  const total=x*y;m={type:'groups',groups:x,size:y,total};q=`Calculate ${x} × ${y}.`;a=`${total}.`;
  if(x>12)m={type:'multiply',a:x,b:y,total};
  if(mode==='double48'){m={type:'double',groups:x,size:4,total:x*8};q=`${x} × 4 = ${x*4}. Find ${x} × 8.`;a=`${x*8}. Double ${x*4}.`;}
  if(mode==='partitionMultiply'){q=`Partition ${x} to calculate ${x} × ${y}.`;a=`${total}. ${Math.floor(x/10)*10}×${y} + ${x%10}×${y}.`;}
  if(mode==='multiplyStory'){q=`${y} boxes hold ${x} pencils each. How many pencils?`;a=`${total} pencils.`;}
  if(kind==='divide'){const d=3+i%2,quotient=low?3+i%4:12+i,rem=mode.startsWith('remainder')?1+i%(d-1):0;const all=quotient*d+rem;m={type:'division',a:all,b:d,total:quotient,remainder:rem};q=`Calculate ${all} ÷ ${d}.`;a=`${quotient}${rem?' remainder '+rem:''}.`;if(mode==='share')q=`Share ${all} counters equally among ${d} children. How many each?`;if(mode==='group')q=`Put ${all} counters in groups of ${d}. How many groups?`;if(mode==='divisionFacts'){m={type:'division',a:total,b:y,total:x,remainder:0};q=`Use ${x} × ${y} = ${total} to find ${total} ÷ ${y}.`;a=x+'.';}if(mode==='remainderStory'){q=`${all} children need cars with ${d} seats each. How many cars are needed?`;a=`${quotient+1} cars. The remaining ${rem} children need another car.`;}}
  if(mode==='scale'||mode==='scaleLength'){q=mode==='scale'?`A recipe uses ${x} eggs. Make ${y} times as much. How many eggs?`:`A ribbon is ${x} cm. Another is ${y} times as long. How long is it?`;a=`${total}${mode==='scaleLength'?' cm':' eggs'}.`;}
  if(mode==='correspondence'){x=2+i%3;y=3+i%3;m={type:'groups',groups:x,size:y,total:x*y};q=`There are ${x} hats and ${y} coats. How many different hat-and-coat outfits?`;a=`${x*y} outfits. Match every hat with each coat.`;}
  if(mode==='missingMult'){q=`___ × ${y} = ${total}.`;a=x+'.';}
 }
 else if(mode.startsWith('money')||mode==='change'){
  kind='money';const x=(low?100:200)+i*23+15,y=40+i*7;let total=x; m={type:'money',a:x,b:y,op:'+',read:mode==='moneyRead'};q=`Write ${x}p in pounds and pence.`;a=money(x)+'.';
  if(mode==='moneyAdd'){total=x+y;q=`Add ${money(x)} and ${y}p.`;a=money(total)+'.';}
  if(mode==='moneySub'){total=x-y;m.op='−';q=`Find ${money(x)} minus ${y}p.`;a=money(total)+'.';}
  if(mode==='change'||mode==='moneyProblem'){m.pay=500;m.op='change';m.b=mode==='moneyProblem'?y:0;total=500-x-m.b;q=`Pay £5 for ${mode==='moneyProblem'?'items costing '+money(x)+' and '+y+'p':'an item costing '+money(x)}. Find the change.`;a=money(total)+'.';}
  m.total=total;
 }
 else if(['millimetres','lengthConvert','lengthCalc','perimeter','missingSide','massScale','massConvert','capacityScale','capacityConvert','measureCalc','fractionLength','drawMeasure','mixedUnits','measureStory','perimeterInvestigate'].includes(mode)){
  kind='measure';const x=3+i%5,y=2+i%3;
  if(['perimeter','missingSide','perimeterInvestigate'].includes(mode)){m={type:'rectangle',a:x+3,b:y,total:2*(x+3+y),missing:mode==='missingSide'};q=mode==='missingSide'?`A rectangle has perimeter ${m.total} cm and length ${m.a} cm. Find its width.`:`Find the perimeter of a rectangle ${m.a} cm long and ${m.b} cm wide.`;a=mode==='missingSide'?`${m.b} cm.`:`${m.total} cm.`;if(mode==='perimeterInvestigate'){q+= ' Draw a different rectangle with the same perimeter.';a+=` For example ${m.a+1} cm by ${m.b-1} cm.`;}}
  else if(['millimetres','massScale','capacityScale'].includes(mode)){const unit=mode==='millimetres'?'mm':mode==='massScale'?'g':'ml',step=mode==='millimetres'?1:100,start=mode==='millimetres'?i%4:0,value=(x+start)*step;m={type:'numberline',start:start*step,end:(start+10)*step,step,value,unit};q=mode==='millimetres'?'The marked point shows a strip end. The strip starts at the first mark. How long is it?':`Read the ${unit==='g'?'mass':'capacity'} shown.`;a=`${mode==='millimetres'?x:value} ${unit}.`;}
  else if(['lengthConvert','massConvert','capacityConvert','mixedUnits'].includes(mode)){const unit=mode==='lengthConvert'||mode==='mixedUnits'?'cm':mode==='massConvert'?'g':'ml',big=unit==='cm'?'m':unit==='g'?'kg':'l',factor=unit==='cm'?100:1000,small=(i+1)*(unit==='cm'?5:50);m={type:'convert',a:x,b:small,factor,unit,big,total:x*factor+small};q=`Write ${x} ${big} ${small} ${unit} in ${unit}.`;a=`${m.total} ${unit}.`;}
  else if(mode==='drawMeasure'){m={type:'ruler',length:30+i*5,unit:'mm'};q=`Use a ruler to draw a line ${m.length} mm long. Label both ends.`;a=`A straight line measuring ${m.length} mm (${m.length/10} cm). Check with a ruler.`;}
  else if(mode==='fractionLength'){kind='fraction';const d=3+i%3,num=low?1:2;m={type:'fractionOf',num,den:d,total:d*(x+2),value:num*(x+2)};q=`Find ${num}/${d} of a ribbon ${m.total} cm long.`;a=`${m.value} cm.`;}
  else {const unit=mode==='lengthCalc'?'cm':'g';m={type:'measureCalc',a:300+i*20,b:125+i*5,op:i%2?'−':'+',unit};m.total=m.op==='+'?m.a+m.b:m.a-m.b;q=`${m.op==='+'?'Combine':'Find the difference between'} ${m.a} ${unit} and ${m.b} ${unit}.`;a=`${m.total} ${unit}.`;}
 }
 else if(['unitFraction','nonUnit','unitOf','fractionOf','tenths','tenthsUp','tenthsDown','fractionLine','beyondWhole','equiv2','equiv3','equiv4','equivMixed','equivExplain','fractionAdd','fractionSub','fractionWhole','fractionMissing','fractionStory','unitCompare','unitOrder','fractionCompare','fractionOrder','fractionReason','fractionReverse'].includes(mode)){
  kind='fraction';let den=low?4:3+i%6,num=mode==='unitFraction'?1:2+i%(den-2);m={type:'fraction',num,den};q=`Shade ${num}/${den} of the strip.`;a=`Shade ${num} of ${den} equal parts.`;
  if(mode==='tenths'){den=10;num=1+i%9;m={type:'fraction',num,den};q=`Shade ${num}/10. How many tenths are unshaded?`;a=`${10-num} tenths remain.`;}
  if(['unitOf','fractionOf','fractionReverse'].includes(mode)){num=mode==='unitOf'||low?1:2;const total=den*(3+i%6);m={type:'fractionOf',num,den,total,value:total/den*num,reverse:mode==='fractionReverse'};q=mode==='fractionReverse'?`1/${den} of a set is ${total/den}. How many in the whole set?`:`Find ${num}/${den} of ${total}.`;a=mode==='fractionReverse'?`${total}.`:`${m.value}.`;}
  if(mode==='tenthsUp'||mode==='tenthsDown'){const start=mode==='tenthsUp'?i:i+4,step=mode==='tenthsUp'?1:-1;m={type:'fractionSequence',den:10,values:Array.from({length:5},(_,j)=>start+j*step),missing:2};q=`Fill the gap: ${m.values.map((v,j)=>j===2?'___':v+'/10').join(', ')}.`;a=m.values[2]+'/10.';}
  if(mode==='fractionLine'||mode==='beyondWhole'){num=mode==='beyondWhole'?den+1+i%(den-1):num;m={type:'fractionLine',num,den,max:mode==='beyondWhole'?2:1};q='Write the fraction at the marked point.';a=`${num}/${den}.`;}
  if(mode.startsWith('equiv')){den=mode==='equiv2'?2:mode==='equiv3'?3:mode==='equiv4'?4:2+i%3;num=1+i%(den-1);m={type:'equivalent',num,den,factor:2};q=`Complete ${num}/${den} = ___/${den*2}. Show it on both strips.`;a=`${num*2}/${den*2}. Each original part splits into two equal parts.`;}
  if(['fractionAdd','fractionSub','fractionWhole','fractionMissing','fractionStory'].includes(mode)){den=low?6:7+i%3;num=2+i%3;const other=1+i%2,sub=mode==='fractionSub';m={type:'fractionCalc',num,den,other,op:sub?'−':'+',value:sub?num-other:num+other};q=`Calculate ${num}/${den} ${m.op} ${other}/${den}.`;a=`${m.value}/${den}.`;if(mode==='fractionWhole'){m.other=den-num;m.value=den;q=`${num}/${den} + ___/${den} = 1.`;a=`${den-num}/${den}.`;}if(mode==='fractionMissing'){q=`${num}/${den} + ___/${den} = ${m.value}/${den}.`;a=`${other}/${den}.`;}if(mode==='fractionStory'){q=`A ribbon is split into ${den} equal parts. Use ${num} parts, then ${other} more. What fraction is used?`;}}
  if(['unitCompare','unitOrder','fractionCompare','fractionOrder','fractionReason'].includes(mode)){const unit=mode.startsWith('unit'),dens=unit?[3,6,4]:[den,den,den],nums=unit?[1,1,1]:[2,1,3];m={type:'fractionCompare',nums,dens};q=mode.endsWith('Order')||mode==='fractionOrder'?`Order ${nums.map((v,j)=>v+'/'+dens[j]).join(', ')} from smallest.`:`Which is greater: ${nums[0]}/${dens[0]} or ${nums[1]}/${dens[1]}? Explain.`;const sorted=nums.map((v,j)=>({v,d:dens[j]})).sort((a,b)=>a.v/a.d-b.v/b.d);a=mode.endsWith('Order')||mode==='fractionOrder'?sorted.map(v=>v.v+'/'+v.d).join(', ')+'.':`${nums[0]}/${dens[0]}. ${unit?'Fewer equal parts means each part is larger.':'The parts are equal-sized; two parts exceed one.'}`;}
 }
 else if(['timeMinute','timeRoman','time24','duration','calendar','durationClock','timeCompare'].includes(mode)){
  kind='time';const hour=1+i%11,minute=low?(i%12)*5:(7+i*7)%60;m={type:'clock',hour,minute,roman:mode==='timeRoman'};q='Write the time on the clock to the nearest minute.';a=`${hour}:${String(minute).padStart(2,'0')}.`;
  if(mode==='time24'){q=`Write ${hour}:${String(minute).padStart(2,'0')} pm using the 24-hour clock.`;a=`${hour+12}:${String(minute).padStart(2,'0')}.`;if(i===0){m.hour=12;m.minute=0;q='Write 12 noon using the 24-hour clock.';a='12:00.';}if(i===1){m.hour=12;m.minute=0;q='Write 12 midnight using the 24-hour clock.';a='00:00.';}}
  if(mode==='duration'){const min=2+i%5;m={type:'convert',a:min,b:0,factor:60,unit:'seconds',big:'minutes',total:min*60};q=`How many seconds are in ${min} minutes?`;a=`${min*60} seconds.`;}
  if(mode==='durationClock'){const add=17+i,start=hour*60+minute,end=start+add;m.add=add;q=`An event starts at ${hour}:${String(minute).padStart(2,'0')} and ends at ${Math.floor(end/60)}:${String(end%60).padStart(2,'0')}. How long is it?`;a=`${add} minutes.`;}
  if(mode==='timeCompare'){m={type:'timeCompare',a:2+i%4,b:(2+i%4)*60+15};q=`Which lasts longer: ${m.a} minutes or ${m.b} seconds? By how much?`;a=`${m.b} seconds, by 15 seconds.`;}
  if(mode==='calendar'){const prompts=[['How many days are in February in a leap year?','29 days.'],['How many days are in a normal year?','365 days.'],['How many days are in a leap year?','366 days.'],['How many days are in April?','30 days.'],['How many days are in July?','31 days.'],['How many days are in September and November?','30 days in each month.'],['How many days are in January and March?','31 days in each month.'],['How many days are in May and August?','31 days in each month.'],['How many days are in October and December?','31 days in each month.'],['How many days are in June and in February in a normal year?','June: 30 days. February: 28 days.']];[q,a]=prompts[i];m={type:'calendar',label:['February: leap year','Normal year','Leap year','April','July','September / November','January / March','May / August','October / December','June / February'][i]};}
 }
 else if(['rightAngle','acute','obtuse','turns','angleSort','drawShape','solid','rotatedSolid','makeSolid','sortShape','horizontal','parallel','perpendicular','linesShape','drawLines','quadrilateral'].includes(mode)){
  kind='shape';
  if(['rightAngle','acute','obtuse','angleSort'].includes(mode)){const angle=mode==='rightAngle'?90:mode==='acute'?45:mode==='obtuse'?120:[45,90,120][i%3];m={type:'angle',angle};q='Is the angle less than, equal to, or greater than a right angle?';a=`${angle<90?'Less than':angle===90?'Equal to':'Greater than'} a right angle.`;}
  else if(mode==='turns'){m={type:'turn',turn:1+i%4};q=`How many right angles make ${['a quarter','a half','three quarters of a','a full'][m.turn-1]} turn?`;a=`${m.turn} right angle${m.turn>1?'s':''}.`;}
  else if(['solid','rotatedSolid','makeSolid'].includes(mode)){const names=['cube','cuboid','triangular prism'],name=names[i%3];m={type:'solid',name,rotated:mode==='rotatedSolid'};q=mode==='makeSolid'?`Use modelling materials to make a ${name}. Record its faces, edges and vertices.`:'Name the solid and count its faces, edges and vertices.';a=name==='triangular prism'?'Triangular prism: 5 faces, 9 edges, 6 vertices.':`${name}: 6 faces, 12 edges, 8 vertices.`;}
  else if(['drawShape','quadrilateral','sortShape'].includes(mode)){m={type:'grid',name:i%2?'rectangle':'square'};q=mode==='quadrilateral'?'Draw two different quadrilaterals. Mark every right angle.':`Draw a ${m.name} on the grid. Mark every right angle.`;a=mode==='quadrilateral'?'For example, a square and a non-square rectangle. Each has four right angles.':`A ${m.name} with four right angles. ${m.name==='square'?'All four sides equal.':'Opposite sides equal.'}`;}
  else {const style=mode==='parallel'?'parallel':mode==='perpendicular'?'perpendicular':mode==='horizontal'?(i%2?'horizontal':'vertical'):'rectangle';m={type:'lines',style:mode==='drawLines'?'crossLines':style};q=mode==='drawLines'?'Draw two parallel lines and a third line perpendicular to both.':'Describe the lines shown. Identify any parallel or perpendicular pairs.';a=style==='parallel'?'The lines are parallel; they stay the same distance apart.':style==='perpendicular'?'The lines are perpendicular; they meet at a right angle.':style==='rectangle'?'Opposite sides are parallel. Adjacent sides are perpendicular.':`Both lines are ${style} and parallel.`;if(mode==='drawLines')a='Two parallel lines crossed at right angles by a third line.';}
 }
 else if(['pictogram','bar','drawBar','table','dataTwo'].includes(mode)){
  kind='data';const key=low?2:[2,5,10][i%3],values=[3+i%3,6+i%3,4+i%3].map(n=>n*key);m={type:'data',mode,labels:['Red','Blue','Green'],values,key};q=mode==='dataTwo'?'How many more votes do red and green have together than blue?':mode==='drawBar'?`Complete the green bar for ${values[2]} votes.`:mode==='table'?'How many votes altogether?':'How many votes for blue?';a=mode==='dataTwo'?`${values[0]+values[2]-values[1]} votes.`:mode==='drawBar'?`A green bar ending at ${values[2]}.`:mode==='table'?`${values.reduce((a,b)=>a+b,0)} votes.`:`${values[1]} votes.`;
 }
 else throw Error('Unknown '+mode);
 if(!q||!a)throw Error('Missing '+mode);steps=guidance[kind]; if(low) q+=' '+({place:'Use the place-value model.',calc:'Work with one place at a time.',multiply:'Count equal groups first.',divide:'Make equal groups first.',fraction:'Count the equal parts first.',measure:'Check the unit and each interval.',money:'Use 100p for each pound.',time:'Find the hour first.',shape:'Trace the sides or lines.',data:'Read the key or scale first.'}[kind]);
 if(level==='higher'){q+=' '+['Explain using the model.','Show how you can check.','Explain one mistake to avoid.','Make a similar example.','Show another method or model.'][i%5];a+=' Accept a correct explanation or matching example.';}
 return {q,a,answer:a,model:m,kind,mode,steps};
}
export function makeLesson(week,day){const [unit,titles,modes]=weeks[week-1],title=titles.split('|')[day-1],mode=modes.split('|')[day-1];const examples=Array.from({length:5},(_,i)=>question(mode,i)),kind=examples[0].kind;const term=week<=10?'Autumn':week<=20?'Spring':'Summer';return {year:3,week,day,term,title,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-'),mode,character:'Tess',objective:/^(Read|Write|Find|Count|Add|Subtract|Compare|Order|Measure|Draw|Recognise|Describe|Make|Sort|Scale|Use|Choose|Explain|Solve|Estimate|Check|Complete|Double|Partition|Multiply|Divide|Share|Group|Interpret|Organise|Investigate) /.test(title)?'To '+title[0].toLowerCase()+title.slice(1)+'.':'To use a clear mathematical model for '+title.toLowerCase()+'.',vocabulary:groups[kind],prior:prior[kind],resources:'Place-value counters, base-ten equipment, fraction strips, ruler, clock or shape models as appropriate.',successCriteria:['I can represent the quantities or properties accurately.','I can explain each step using the model.','I can check my answer and use the correct units.'],misconception:mis[kind],check:guidance[kind][3],warmup:prior[kind]+' Ask pupils to show an example.',teacherModel:guidance[kind],guided:examples[1].q,independent:'Pause at You do. Pupils try first, then discuss the revealed steps. Select the appropriate worksheet.',plenary:examples[4].q,preteach:{focus:prior[kind],steps:guidance[kind].slice(0,3),questions:Array.from({length:3},(_,i)=>question(mode,i,'lower'))},lower:Array.from({length:5},(_,i)=>question(mode,i+5,'lower')),expected:Array.from({length:5},(_,i)=>question(mode,i+5)),higher:Array.from({length:5},(_,i)=>question(mode,i+5,'higher')),examples,curriculumSource:source};}
const root='.qa/year3-maths';await fs.mkdir(root,{recursive:true});const lessons=weeks.flatMap((_,w)=>Array.from({length:5},(_,d)=>makeLesson(w+1,d+1)));await fs.writeFile(root+'/lessons.json',JSON.stringify(lessons,null,2));await fs.writeFile(root+'/curriculum.json',JSON.stringify(weeks.map(([unit,titles],w)=>({week:w+1,term:w<10?'Autumn':w<20?'Spring':'Summer',unit,days:titles.split('|')})),null,2));console.log('Prepared '+lessons.length+' Year 3 lessons.');
