import fs from 'node:fs/promises';

export const source='https://www.gov.uk/government/publications/national-curriculum-in-england-mathematics-programmes-of-study/national-curriculum-in-england-mathematics-programmes-of-study#year-5-programme-of-study';

const weeks=[
['Place value to 1,000,000','Read write order and compare numbers|Determine the value of every digit|Count in powers of ten|Use negative numbers in context|Read Roman numerals to 1,000','placeMillion|digitMillion|powersTen|negative5|roman1000'],
['Rounding and place-value problems','Round to 10 100 and 1,000|Round to 10,000 and 100,000|Choose an appropriate rounding degree|Solve place-value problems|Explain number patterns and boundaries','roundSmall5|roundLarge5|roundChoose5|placeProblem5|placeReason5'],
['Addition and subtraction','Add whole numbers with more than four digits|Subtract whole numbers with more than four digits|Calculate mentally with large numbers|Use rounding to check calculations|Solve multi-step addition and subtraction problems','addLarge5|subLarge5|mentalLarge5|roundCheck5|addSubProblem5'],
['Formal multiplication','Multiply four digits by one digit|Multiply two digits by two digits|Multiply three digits by two digits|Multiply four digits by two digits|Solve formal multiplication problems','multiply4x1|multiply2x2|multiply3x2|multiply4x2|multiplyProblem5'],
['Division and mental calculation','Use short division with exact answers|Interpret remainders in context|Multiply and divide mentally from known facts|Multiply and divide by 10 100 and 1,000|Solve division problems','shortDivision5|divisionRemainder5|mentalMultiplyDivide5|scalePowers5|divisionProblem5'],
['Factors multiples primes squares and cubes','Identify multiples and factors|Find factor pairs and common factors|Recognise prime and composite numbers|Use square and cube numbers and notation|Solve number-property problems','multiplesFactors5|commonFactors5|primeComposite5|squareCube5|numberPropertyProblem5'],
['Multiplication and division reasoning','Solve scaling problems|Solve problems involving simple rates|Use distributive and associative relationships|Solve problems using all four operations|Choose an efficient strategy','scaling5|rates5|distributive5|fourOperations5|efficientStrategy5'],
['Equivalent improper and mixed fractions','Identify equivalent fractions visually|Compare fractions with related denominators|Order fractions with related denominators|Convert improper fractions to mixed numbers|Convert mixed numbers to improper fractions','equivVisual5|fractionCompare5|fractionOrder5|improperToMixed5|mixedToImproper5'],
['Add and subtract fractions','Add fractions with the same denominator|Add fractions with related denominators|Subtract fractions with related denominators|Add and subtract mixed numbers|Solve fraction calculation problems','fractionAddSame5|fractionAddRelated5|fractionSubRelated5|mixedFractionCalc5|fractionProblem5'],
['Multiply fractions by whole numbers','Represent fraction multiplication|Multiply proper fractions by whole numbers|Multiply mixed numbers by whole numbers|Simplify fraction products|Solve fraction scaling problems','fractionMultiplyRepresent5|fractionMultiply5|mixedMultiply5|simplifyProduct5|fractionScaling5'],
['Decimals to three places','Write decimals as fractions|Connect tenths hundredths and thousandths|Read write order and compare three-place decimals|Round decimals to a whole number and one place|Solve problems with three-place decimals','decimalFraction5|thousandths5|decimalCompare5|decimalRound5|decimalProblem5'],
['Percentages and equivalents','Understand per cent as parts per hundred|Connect fractions decimals and percentages|Recall benchmark fraction percentage equivalents|Find percentages of quantities|Solve percentage problems','percentMeaning5|fdpConnect5|benchmarkPercent5|percentOf5|percentProblem5'],
['Fractions decimals and percentages','Convert fractions to decimals|Convert decimals to fractions|Compare fractions decimals and percentages|Find missing equivalent values|Solve mixed equivalence problems','fractionToDecimal5|decimalToFraction5|fdpCompare5|fdpMissing5|fdpProblem5'],
['Metric measure and conversion','Convert kilometres and metres|Convert metres centimetres and millimetres|Convert kilograms and grams|Convert litres and millilitres|Use decimal notation in metric conversions','kmM5|mCmMm5|kgG5|lMl5|metricDecimal5'],
['Imperial measure time and conversion','Use approximate metric and imperial equivalents|Convert between units of time|Solve elapsed-time problems|Use all four operations with measures|Solve multi-step conversion problems','imperial5|timeConvert5|elapsedTime5|measureOperations5|conversionProblem5'],
['Perimeter of rectilinear shapes','Calculate perimeter of rectangles|Calculate perimeter of composite rectilinear shapes|Find missing lengths from a perimeter|Compare shapes with the same perimeter|Solve perimeter problems','perimeterRectangle5|perimeterComposite5|perimeterMissing5|samePerimeter5|perimeterProblem5'],
['Area of rectangles and squares','Calculate area of rectangles|Calculate area of squares|Estimate the area of irregular shapes|Compare shapes with the same area|Solve area and scale problems','areaRectangle5|areaSquare5|areaEstimate5|sameArea5|areaProblem5'],
['Volume and capacity','Estimate volume using cubic centimetres|Build cuboids from unit cubes|Compare volume and capacity|Find missing cuboid dimensions|Solve volume and capacity problems','volumeEstimate5|volumeCuboid5|volumeCapacity5|volumeMissing5|volumeProblem5'],
['Angles in degrees','Estimate and compare angles|Measure angles in degrees|Draw angles accurately|Use angles around a point and on a line|Use other multiples of 90 degrees','angleEstimate5|angleMeasure5|angleDraw5|angleFacts5|angleNinety5'],
['Properties of shapes','Identify 3-D shapes from 2-D representations|Use rectangle properties to find missing lengths and angles|Distinguish regular and irregular polygons|Classify 2-D and 3-D shapes|Solve shape-property problems','solidFrom2D5|rectangleProperties5|regularIrregular5|classifyShapes5|shapeProblem5'],
['Coordinates reflection and translation','Read and plot coordinates|Translate shapes on a grid|Reflect shapes across an axis|Describe position after a transformation|Solve coordinate problems','coordinatePlot5|translate5|reflect5|transformationDescribe5|coordinateProblem5'],
['Line graphs','Read a line graph|Solve comparison questions from line graphs|Solve sum and difference questions|Complete a line graph|Choose and explain a graph scale','lineGraphRead5|lineGraphCompare5|lineGraphSum5|lineGraphComplete5|lineGraphScale5'],
['Tables and timetables','Read information from tables|Complete a table|Read and interpret timetables|Solve timetable duration problems|Solve multi-step table problems','tableRead5|tableComplete5|timetableRead5|timetableDuration5|tableProblem5'],
['Financial and multi-step problems','Solve money problems with four operations|Solve addition and subtraction multi-step problems|Solve multiplication and division multi-step problems|Decide which operations are needed|Explain and check a multi-step solution','moneyFourOps5|addSubMulti5|multDivMulti5|chooseOperations5|checkMulti5'],
['Number consolidation','Place value and negative-number review|Rounding and calculation review|Formal multiplication review|Short division review|Factors primes squares and cubes review','negative5|roundLarge5|multiply4x2|shortDivision5|numberPropertyProblem5'],
['Fraction decimal and percentage consolidation','Equivalent and mixed-fraction review|Fraction calculation review|Decimal place-value review|Percentage equivalence review|Mixed FDP reasoning','mixedToImproper5|fractionAddRelated5|decimalCompare5|benchmarkPercent5|fdpProblem5'],
['Measure consolidation','Metric conversion review|Imperial equivalence review|Perimeter and area review|Volume and capacity review|Time conversion review','metricDecimal5|imperial5|areaProblem5|volumeProblem5|timeConvert5'],
['Geometry and statistics consolidation','Angle reasoning review|Shape-property review|Coordinate transformation review|Line-graph review|Table and timetable review','angleFacts5|regularIrregular5|reflect5|lineGraphSum5|timetableDuration5'],
['Mathematical reasoning investigations','Investigate factors and multiples|Investigate fraction equivalence|Investigate area and perimeter|Investigate transformations|Investigate data and measures','commonFactors5|fdpMissing5|sameArea5|transformationDescribe5|lineGraphCompare5'],
['End-of-year assessment and transition','Assess number and calculation|Assess fractions decimals and percentages|Assess measurement|Assess geometry and statistics|Reason explain and prepare for Year 6','fourOperations5|fdpProblem5|conversionProblem5|coordinateProblem5|checkMulti5']
];

const vocab={place:['place value','million','power of ten','negative','Roman numeral'],calc:['sum','difference','inverse','estimate','operation'],multiply:['factor','multiple','product','prime','composite'],divide:['dividend','divisor','quotient','remainder','inverse'],fraction:['numerator','denominator','equivalent','improper fraction','mixed number'],decimal:['tenths','hundredths','thousandths','decimal place','round'],percent:['percent','hundredths','equivalent','fraction','decimal'],measure:['convert','metric','imperial','perimeter','area','volume'],time:['duration','timetable','seconds','minutes','hours'],shape:['degree','angle','regular','irregular','property'],coordinate:['coordinate','translate','reflect','axis','transformation'],data:['axis','scale','interval','line graph','timetable'],money:['pounds','pence','total','change','estimate']};
const prior={place:'Recall four-digit place value, rounding and counting through zero.',calc:'Align place-value columns and estimate before calculating.',multiply:'Recall multiplication and division facts to 12 × 12.',divide:'Connect division to multiplication and interpret a remainder.',fraction:'Recognise equivalent fractions and fractions greater than one.',decimal:'Recall tenths and hundredths as fractions and decimals.',percent:'Recall that a whole is 100 hundredths.',measure:'Choose a suitable unit and convert to a common unit.',time:'Read analogue and digital time and use 60 minutes in an hour.',shape:'Recall angle types, parallel lines and properties of polygons.',coordinate:'Plot points in the first quadrant and describe translations.',data:'Read titles, labels, keys and scales accurately.',money:'Use decimal notation for pounds and pence.'};
const guidance={place:['Represent the number and name every place.','Identify the required change or comparison.','Work with one place or interval at a time.','Check against the size and context of the number.'],calc:['Estimate the answer first.','Choose and set out an efficient method.','Complete each operation in order.','Check with an inverse or a second strategy.'],multiply:['Identify factors, multiples and known facts.','Partition or use a formal layout.','Combine partial products accurately.','Check with division or estimation.'],divide:['Estimate the quotient.','Use a formal or mental division strategy.','Interpret any remainder in context.','Multiply to check the quotient.'],fraction:['Represent each fraction with equal parts.','Create a common denominator when needed.','Calculate the numerators carefully.','Simplify and check the size of the answer.'],decimal:['Align decimal places and name each digit.','Use place value to compare or calculate.','Apply the required rounding boundary.','Check the answer against the original number.'],percent:['Write the percentage as parts per hundred.','Connect it to a fraction and decimal.','Use a known benchmark or find one per cent.','Check the result against the whole.'],measure:['Write the conversion fact.','Convert quantities to the same unit.','Calculate and restore the correct unit.','Estimate whether the result is sensible.'],time:['Put both times or durations in one unit.','Use a timeline or timetable.','Calculate each interval carefully.','Convert back and check the units.'],shape:['Mark the known dimensions, angles or properties.','Use a ruler, protractor, grid or model.','Apply the relevant geometric fact.','Check every stated property.'],coordinate:['Read across then up.','Apply one transformation at a time.','Plot every vertex accurately.','Check distances from the axis or translation vector.'],data:['Read the title, axes and scale.','Extract the relevant values.','Calculate the requested comparison or total.','Check the answer against the graph or table.'],money:['Convert to one money unit if helpful.','Choose the required operations.','Calculate with aligned decimal places.','Use estimation to check the total or change.']};
const misconceptions={place:'A pupil ignores a zero placeholder or changes the wrong place when multiplying by ten.',calc:'A pupil applies an operation correctly but misaligns the place-value columns.',multiply:'A pupil lists some factors but does not check systematically for all factor pairs.',divide:'A pupil gives a remainder without deciding what it means in the problem.',fraction:'A pupil adds denominators when combining fractions.',decimal:'A pupil compares decimal digits without considering their place value.',percent:'A pupil treats a percentage as an amount without identifying the whole.',measure:'A pupil combines measurements written in different units.',time:'A pupil treats time as base ten instead of using sixty.',shape:'A pupil judges a shape by appearance instead of testing its properties.',coordinate:'A pupil changes the shape while translating or reflects from the wrong axis.',data:'A pupil counts gridlines rather than intervals or ignores the scale.',money:'A pupil omits the zero in money notation, changing the value.'};

const gcd=(a,b)=>b?gcd(b,a%b):a;
const frac=(n,d)=>{const g=gcd(Math.abs(n),Math.abs(d));return `${n/g}/${d/g}`};
const roman=n=>{const map=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let s='';for(const [v,c] of map)while(n>=v){s+=c;n-=v}return s};
const ones=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];
const tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];
const words=n=>{if(n<20)return ones[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?'-'+ones[n%10]:'');if(n<1000)return ones[Math.floor(n/100)]+' hundred'+(n%100?' and '+words(n%100):'');if(n<1000000)return words(Math.floor(n/1000))+' thousand'+(n%1000?' '+words(n%1000):'');return words(Math.floor(n/1000000))+' million'+(n%1000000?' '+words(n%1000000):'')};
const pairs=n=>{const out=[];for(let d=1;d<=Math.sqrt(n);d++)if(n%d===0)out.push(`${d} × ${n/d}`);return out.join(', ')};
const isPrime=n=>n>1&&Array.from({length:Math.max(0,Math.floor(Math.sqrt(n))-1)},(_,i)=>i+2).every(d=>n%d);
const slugify=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

const domains={
 place:['placeMillion','digitMillion','powersTen','negative5','roman1000','roundSmall5','roundLarge5','roundChoose5','placeProblem5','placeReason5'],
 calc:['addLarge5','subLarge5','mentalLarge5','roundCheck5','addSubProblem5','fourOperations5','efficientStrategy5','addSubMulti5','multDivMulti5','chooseOperations5','checkMulti5'],
 multiply:['multiply4x1','multiply2x2','multiply3x2','multiply4x2','multiplyProblem5','multiplesFactors5','commonFactors5','primeComposite5','squareCube5','numberPropertyProblem5','scaling5','rates5','distributive5'],
 divide:['shortDivision5','divisionRemainder5','mentalMultiplyDivide5','scalePowers5','divisionProblem5'],
 fraction:['equivVisual5','fractionCompare5','fractionOrder5','improperToMixed5','mixedToImproper5','fractionAddSame5','fractionAddRelated5','fractionSubRelated5','mixedFractionCalc5','fractionProblem5','fractionMultiplyRepresent5','fractionMultiply5','mixedMultiply5','simplifyProduct5','fractionScaling5'],
 decimal:['decimalFraction5','thousandths5','decimalCompare5','decimalRound5','decimalProblem5','fractionToDecimal5','decimalToFraction5'],
 percent:['percentMeaning5','fdpConnect5','benchmarkPercent5','percentOf5','percentProblem5','fdpCompare5','fdpMissing5','fdpProblem5'],
 measure:['kmM5','mCmMm5','kgG5','lMl5','metricDecimal5','imperial5','measureOperations5','conversionProblem5','perimeterRectangle5','perimeterComposite5','perimeterMissing5','samePerimeter5','perimeterProblem5','areaRectangle5','areaSquare5','areaEstimate5','sameArea5','areaProblem5','volumeEstimate5','volumeCuboid5','volumeCapacity5','volumeMissing5','volumeProblem5'],
 time:['timeConvert5','elapsedTime5','timetableRead5','timetableDuration5'],
 shape:['angleEstimate5','angleMeasure5','angleDraw5','angleFacts5','angleNinety5','solidFrom2D5','rectangleProperties5','regularIrregular5','classifyShapes5','shapeProblem5'],
 coordinate:['coordinatePlot5','translate5','reflect5','transformationDescribe5','coordinateProblem5'],
 data:['lineGraphRead5','lineGraphCompare5','lineGraphSum5','lineGraphComplete5','lineGraphScale5','tableRead5','tableComplete5','tableProblem5'],
 money:['moneyFourOps5']
};
const domainFor=mode=>Object.entries(domains).find(([,modes])=>modes.includes(mode))?.[0]??'calc';

function makeQuestion(mode,index,level='expected'){
 const i=index%10,low=level==='lower',hard=level==='higher',kind=domainFor(mode);let q='',a='',model={};
 const challenge=()=>{if(low)q+=' Use the representation to help.';if(hard){q+=' Explain or prove your answer.';a+=' Accept a correct explanation.'}};
 if(domains.place.includes(mode)){
  const n=(low?120000:hard?720000:340000)+i*7319+482;model={type:'place',n};q=`Partition ${n.toLocaleString('en-GB')} by place value.`;a=`${Math.floor(n/100000)*100000} + ${Math.floor(n/10000)%10*10000} + ${Math.floor(n/1000)%10*1000} + ${Math.floor(n/100)%10*100} + ${Math.floor(n/10)%10*10} + ${n%10}.`;
  if(mode==='placeMillion'){q=i%2?`Write ${n.toLocaleString('en-GB')} in words.`:`Order ${n.toLocaleString('en-GB')}, ${(n+9000).toLocaleString('en-GB')} and ${(n-7000).toLocaleString('en-GB')}.`;a=i%2?words(n)+'.':[n-7000,n,n+9000].map(v=>v.toLocaleString('en-GB')).join(', ')+'.';}
  if(mode==='digitMillion'){const p=[100000,10000,1000,100,10,1][i%6],d=Math.floor(n/p)%10;q=`What is the value of the digit ${d} in ${n.toLocaleString('en-GB')}?`;a=`${(d*p).toLocaleString('en-GB')}.`;}
  if(mode==='powersTen'){const start=23+i,step=10**(2+i%4),values=Array.from({length:5},(_,j)=>start+j*step);model={type:'sequence',values,missing:3};q=`Continue in steps of ${step.toLocaleString('en-GB')}: ${values.slice(0,3).join(', ')}, ___, ${values[4].toLocaleString('en-GB')}.`;a=`${values[3].toLocaleString('en-GB')}.`;}
  if(mode==='negative5'){const start=-15,end=15,value=-8+i;model={type:'numberline',start,end,value,step:3};q=`A temperature changes from ${value}°C to ${value+7}°C. What is the change?`;a='An increase of 7°C.';}
  if(mode==='roman1000'){const value=100+i*73;model={type:'sequence',values:[roman(value-1),roman(value),roman(value+1)],missing:1};q=`Write ${value} in Roman numerals.`;a=roman(value)+'.';}
  if(mode.startsWith('round')){const unit=mode==='roundSmall5'?[10,100,1000][i%3]:mode==='roundLarge5'?[10000,100000][i%2]:[100,1000,10000,100000][i%4],rounded=Math.round(n/unit)*unit;model={type:'numberline',start:Math.floor(n/unit)*unit,end:Math.floor(n/unit)*unit+unit,value:n,step:unit/10};q=`Round ${n.toLocaleString('en-GB')} to the nearest ${unit.toLocaleString('en-GB')}.`;a=`${rounded.toLocaleString('en-GB')}.`;}
  if(mode==='placeProblem5'){const total=n+100000-10000;q=`A counter starts at ${n.toLocaleString('en-GB')}. Add 100,000 and subtract 10,000. Where does it finish?`;a=`${total.toLocaleString('en-GB')}.`;model={type:'sequence',values:[n,n+100000,total],missing:2};}
  if(mode==='placeReason5'){const step=10**(2+i%4),values=[n,n+step,n+2*step,n+3*step,n+4*step];model={type:'sequence',values,missing:3};q=`Find the missing term and explain the rule: ${values.slice(0,3).join(', ')}, ___, ${values[4]}.`;a=`${values[3]}; add ${step.toLocaleString('en-GB')}.`;}
 }
 else if(domains.calc.includes(mode)){
  let x=(low?12340:hard?483219:75320)+i*1731,y=(low?2380:hard?192784:18640)+i*619,op=mode.includes('sub')?'−':'+';if(op==='−'&&y>x)[x,y]=[y,x];let total=op==='+'?x+y:x-y;model={type:'calculation',a:x,b:y,op,total};q=`Calculate ${x.toLocaleString('en-GB')} ${op} ${y.toLocaleString('en-GB')}.`;a=`${total.toLocaleString('en-GB')}.`;
  if(mode==='mentalLarge5'){x=25000+i*1000+498;y=502+i;total=x+y;model={type:'compensate',a:x,b:y,total};q=`Calculate ${x.toLocaleString('en-GB')} + ${y} mentally.`;a=`${total.toLocaleString('en-GB')}. Compensate to a multiple of 1,000.`;}
  if(mode==='roundCheck5'){q=`Estimate, calculate and check ${x.toLocaleString('en-GB')} + ${y.toLocaleString('en-GB')}.`;a=`${(x+y).toLocaleString('en-GB')}. A rounded estimate and inverse check should agree.`;}
  if(['addSubProblem5','addSubMulti5','multDivMulti5','chooseOperations5','checkMulti5','fourOperations5'].includes(mode)){const z=1200+i*73;model={type:'twoStep',a:x,b:y,c:z,total:x+y-z};q=`A project had ${x.toLocaleString('en-GB')} items, received ${y.toLocaleString('en-GB')} more and used ${z.toLocaleString('en-GB')}. How many remain?`;a=`${(x+y-z).toLocaleString('en-GB')}.`;}
  if(mode==='efficientStrategy5'){q=`Choose an efficient method for ${x.toLocaleString('en-GB')} + ${y.toLocaleString('en-GB')}.`;a=`${(x+y).toLocaleString('en-GB')}. Accept a correct efficient strategy.`;}
 }
 else if(domains.multiply.includes(mode)||domains.divide.includes(mode)){
  let x=low?234+i*7:hard?2345+i*31:1243+i*19,y=mode==='multiply4x1'?3+i%6:12+i%7,total=x*y;model={type:'multiply',a:x,b:y,total};q=`Calculate ${x.toLocaleString('en-GB')} × ${y} using a formal method.`;a=`${total.toLocaleString('en-GB')}.`;
  if(mode==='multiply2x2'){x=23+i*3;y=14+i%6;total=x*y;model={type:'multiply',a:x,b:y,total};q=`Calculate ${x} × ${y}.`;a=`${total}.`;}
  if(mode==='multiply3x2'){x=234+i*17;y=21+i%8;total=x*y;model={type:'multiply',a:x,b:y,total};q=`Calculate ${x} × ${y}.`;a=`${total.toLocaleString('en-GB')}.`;}
  if(mode==='multiplyProblem5'){q=`A theatre has ${y} rows of ${x.toLocaleString('en-GB')} seats. How many seats?`;a=`${total.toLocaleString('en-GB')} seats.`;}
  if(domains.divide.includes(mode)){const divisor=2+i%8,quot=(low?132:hard?1203:423)+i*9,remainder=mode==='divisionRemainder5'?1+i%Math.max(1,divisor-1):0,dividend=divisor*quot+remainder;model={type:'division',a:dividend,b:divisor,total:quot,remainder};q=`Calculate ${dividend.toLocaleString('en-GB')} ÷ ${divisor}.`;a=`${quot.toLocaleString('en-GB')}${remainder?' remainder '+remainder:''}.`;if(mode==='divisionRemainder5'){q=`${dividend} pupils travel in minibuses holding ${divisor}. How many minibuses are needed?`;a=`${quot+(remainder?1:0)} minibuses.`;}}
  if(mode==='scalePowers5'){const value=Number((1.25+i*.37).toFixed(2)),factor=[10,100,1000][i%3],product=Number((value*factor).toFixed(6)),quotient=Number((value/factor).toFixed(6));model={type:'numbers',values:[value,product,quotient]};q=`Calculate ${value} × ${factor} and ${value} ÷ ${factor}.`;a=`${product} and ${quotient}.`;}
  if(mode==='mentalMultiplyDivide5'){const f=6+i%7,n=f*(20+i);model={type:'division',a:n,b:f,total:n/f,remainder:0};q=`Use known facts to calculate ${n} ÷ ${f}.`;a=`${n/f}.`;}
  if(mode==='multiplesFactors5'){const n=24+i*6;model={type:'groups',groups:6,size:n/6,total:n};q=`List the first five multiples of ${2+i%7} and decide whether ${n} is a multiple.`;const f=2+i%7;a=`${[1,2,3,4,5].map(v=>v*f).join(', ')}; ${n%f===0?'yes':'no'}.`;}
  if(mode==='commonFactors5'){const n=24+i*2,m=36+i*3;model={type:'numbers',values:[n,m]};q=`Find the common factors of ${n} and ${m}.`;const cf=[];for(let d=1;d<=Math.min(n,m);d++)if(n%d===0&&m%d===0)cf.push(d);a=cf.join(', ')+'.';}
  if(mode==='primeComposite5'){const n=11+i;model={type:'numbers',values:[n]};q=`Is ${n} prime or composite? Justify using factors.`;a=`${isPrime(n)?'Prime':'Composite'}. Factor pairs: ${pairs(n)}.`;}
  if(mode==='squareCube5'){const n=2+i%6;model={type:'groups',groups:n,size:n,total:n*n};q=`Calculate ${n}² and ${n}³.`;a=`${n*n} and ${n*n*n}.`;}
  if(mode==='numberPropertyProblem5'){const n=36+i*4;model={type:'numbers',values:[n]};q=`Find every factor pair of ${n}, then state whether it is square, cube, prime or composite.`;a=`${pairs(n)}; ${Number.isInteger(Math.sqrt(n))?'square and ':''}composite.`;}
  if(mode==='scaling5'){x=12+i;y=3+i%4;model={type:'multiply',a:x,b:y,total:x*y};q=`One ribbon is ${x} cm. Another is ${y} times as long. Find its length.`;a=`${x*y} cm.`;}
  if(mode==='rates5'){x=3+i%4;y=12+i*2;model={type:'division',a:y*x,b:x,total:y,remainder:0};q=`${x} identical items cost £${(y*x).toFixed(2)}. Find the cost of one.`;a=`£${y.toFixed(2)}.`;}
  if(mode==='distributive5'){x=31+i;y=4+i%4;model={type:'multiply',a:x,b:y,total:x*y};q=`Use partitioning to calculate ${x} × ${y}.`;a=`30 × ${y} + ${x-30} × ${y} = ${x*y}.`;}
 }
 else if(domains.fraction.includes(mode)){
  const den=[4,5,6,8,10][i%5],num=1+i%(den-1);model={type:'fraction',num,den};q=`Represent ${num}/${den}.`;a=`${num}/${den}.`;
  if(mode==='equivVisual5'){const factor=2+i%3;model={type:'equivalent',num,den,factor};q=`Complete ${num}/${den} = ___/${den*factor}.`;a=`${num*factor}/${den*factor}.`;}
  if(mode==='fractionCompare5'||mode==='fractionOrder5'){const d1=3+i%3,d2=d1*2,n1=1+i%(d1-1),n2=1+(i+1)%(d2-1);model={type:'fractionCompare',nums:[n1,n2],dens:[d1,d2]};q=mode==='fractionCompare5'?`Compare ${n1}/${d1} and ${n2}/${d2} using <, > or =.`:`Order ${n1}/${d1}, ${n2}/${d2} and ${(n1+1)}/${d1} from smallest.`;const vals=[[n1/d1,`${n1}/${d1}`],[n2/d2,`${n2}/${d2}`],[(n1+1)/d1,`${n1+1}/${d1}`]];a=mode==='fractionCompare5'?`${n1/d1<n2/d2?'<':n1/d1>n2/d2?'>':'='}.`:vals.sort((x,y)=>x[0]-y[0]).map(v=>v[1]).join(', ')+'.';}
  if(mode==='improperToMixed5'||mode==='mixedToImproper5'){const whole=1+i%3,d=4+i%4,n=1+i%(d-1),imp=whole*d+n;model={type:'numbers',values:[whole,n,d,imp]};q=mode==='improperToMixed5'?`Convert ${imp}/${d} to a mixed number.`:`Convert ${whole} ${n}/${d} to an improper fraction.`;a=mode==='improperToMixed5'?`${whole} ${n}/${d}.`:`${imp}/${d}.`;}
  if(mode.startsWith('fractionAdd')||mode==='fractionSubRelated5'||mode==='mixedFractionCalc5'||mode==='fractionProblem5'){let d=6+i%3,n1=1+i%2,n2=2+i%3,op=mode==='fractionSubRelated5'?'−':'+';if(op==='−')n1=n2+2;model={type:'fractionCalc',num:n1,other:n2,den:d,op,value:op==='+'?n1+n2:n1-n2};q=`Calculate ${n1}/${d} ${op} ${n2}/${d}.`;a=`${frac(model.value,d)}.`;if(mode==='fractionAddRelated5'||mode==='fractionSubRelated5'){const small=d/2,smallNum=1;q=`Calculate ${smallNum}/${small} ${op} ${n2}/${d}.`;const total=op==='+'?smallNum*2+n2:smallNum*2-n2;model={type:'fractionCalc',num:smallNum*2,other:n2,den:d,op,value:total};a=`${frac(total,d)}.`;}if(mode==='mixedFractionCalc5'){q=`Calculate 1 ${n1}/${d} + 2 ${n2}/${d}.`;a=`3 ${frac(n1+n2,d)} (convert if improper).`;}}
  if(mode.includes('Multiply')||mode==='simplifyProduct5'||mode==='fractionScaling5'){const d=5+i%4,n=1+i%Math.max(1,d-2),whole=2+i%3,value=n*whole;model={type:'fractionCalc',num:n,other:n*(whole-1),den:d,op:'+',value};q=`Calculate ${n}/${d} × ${whole}.`;a=`${frac(value,d)}.`;if(mode==='mixedMultiply5'){q=`Calculate 1 ${n}/${d} × ${whole}.`;const imp=d+n,prod=imp*whole;a=`${Math.floor(prod/d)} ${prod%d?frac(prod%d,d):''}`.trim()+'.';model={type:'numbers',values:[imp,whole,prod,d]};}}
 }
 else if(domains.decimal.includes(mode)||domains.percent.includes(mode)){
  const value=Number((0.125+i*.073).toFixed(3));model={type:'numberline',start:0,end:1,value,step:.1};q=`Write ${value} as a fraction with denominator 1,000.`;a=`${Math.round(value*1000)}/1000.`;
  if(mode==='thousandths5'){q=`What is the value of each digit in ${value}?`;a=`${Math.floor(value*10)%10} tenths, ${Math.floor(value*100)%10} hundredths and ${Math.floor(value*1000)%10} thousandths.`;}
  if(mode==='decimalCompare5'||mode==='fdpCompare5'){const b=Number((value+.021).toFixed(3));model={type:'numbers',values:[value,b]};q=`Write <, > or =: ${value} ___ ${b}.`;a='<.';}
  if(mode==='decimalRound5'){q=`Round ${value} to one decimal place.`;a=`${value.toFixed(1)}.`;}
  if(mode==='decimalProblem5'){const x=Number((1.235+i*.11).toFixed(3)),y=Number((0.321+i*.017).toFixed(3));model={type:'calculation',a:x,b:y,op:'+',total:Number((x+y).toFixed(3))};q=`Calculate ${x} + ${y}.`;a=`${model.total}.`;}
  if(mode==='fractionToDecimal5'||mode==='decimalToFraction5'){const d=[2,4,5,10][i%4],n=1+i%(d-1),v=n/d;model={type:'fractionLine',num:n,den:d,max:1};q=mode==='fractionToDecimal5'?`Write ${n}/${d} as a decimal.`:`Write ${v} as a fraction in simplest form.`;a=mode==='fractionToDecimal5'?`${v}.`:`${frac(n,d)}.`;}
  if(domains.percent.includes(mode)){const pct=[10,20,25,40,50,60,75,80][i%8],whole=(low?40:hard?360:120)+i*20;model={type:'fractionOf',num:pct,den:100,total:whole,value:whole*pct/100,reverse:false};q=`Find ${pct}% of ${whole}.`;a=`${whole*pct/100}.`;if(mode==='percentMeaning5'){q=`Write ${pct}% as a fraction out of 100 and as a decimal.`;a=`${pct}/100 and ${pct/100}.`;}if(mode==='benchmarkPercent5'||mode==='fdpConnect5'){const map={10:'1/10',20:'1/5',25:'1/4',40:'2/5',50:'1/2',60:'3/5',75:'3/4',80:'4/5'};q=`Complete: ${pct}% = ___ = ${pct/100}.`;a=`${map[pct]}.`;}if(mode==='fdpMissing5'||mode==='fdpProblem5'){q=`A class has ${whole} pupils. ${pct}% chose option A. How many pupils is that?`;a=`${whole*pct/100} pupils.`;}}
 }
 else if(domains.measure.includes(mode)||domains.time.includes(mode)||domains.money.includes(mode)){
  const maps={kmM5:[1000,'metres','kilometres'],mCmMm5:[100,'centimetres','metres'],kgG5:[1000,'grams','kilograms'],lMl5:[1000,'millilitres','litres'],metricDecimal5:[1000,'metres','kilometres']};
  if(maps[mode]){const [factor,unit,big]=maps[mode],x=2+i%6,b=Math.round((i%4)*factor/10),total=x*factor+b;model={type:'convert',a:x,b,factor,unit,big,total};q=`Convert ${x} ${big}${b?' and '+b+' '+unit:''} to ${unit}.`;a=`${total.toLocaleString('en-GB')} ${unit}.`;}
  else if(mode==='imperial5'){const miles=5+i,km=Math.round(miles*1.6);model={type:'convert',a:miles,b:0,factor:1.6,unit:'kilometres',big:'miles',total:miles*1.6};q=`Use 5 miles ≈ 8 km to estimate ${miles} miles in kilometres.`;a=`About ${km} km.`;}
  else if(domains.time.includes(mode)){const hour=9+i%6,minute=(i*7)%60,add=35+i*5;model={type:'clock',hour,minute,add};q=`A lesson starts at ${hour}:${String(minute).padStart(2,'0')} and lasts ${add} minutes. When does it finish?`;const end=hour*60+minute+add;a=`${Math.floor(end/60)}:${String(end%60).padStart(2,'0')}.`;if(mode==='timeConvert5'){model={type:'convert',a:2+i%5,b:0,factor:60,unit:'minutes',big:'hours',total:(2+i%5)*60};q=`Convert ${model.a} hours to minutes.`;a=`${model.total} minutes.`;}if(mode.startsWith('timetable')){model={type:'data',mode:'table',labels:['09:15','10:05','11:20'],values:[50,75,45],key:5};q=mode==='timetableRead5'?'Read the second departure time from the timetable.':'A journey starts at 09:15 and lasts 50 minutes. When does it finish?';a=mode==='timetableRead5'?'10:05.':'10:05.';}}
  else if(mode.startsWith('perimeter')||mode==='samePerimeter5'){const x=6+i,y=4+i%4,total=2*(x+y);model={type:'rectangle',a:x,b:y,total,missing:mode==='perimeterMissing5'};q=mode==='perimeterMissing5'?`A rectangle has perimeter ${total} cm and length ${x} cm. Find its width.`:`Find the perimeter of a rectangle ${x} cm by ${y} cm.`;a=mode==='perimeterMissing5'?`${y} cm.`:`${total} cm.`;if(mode==='perimeterComposite5'){q=`A rectilinear L-shape has outer side lengths ${x}, ${y}, ${x+2}, ${y+2}, 2 and 2 cm. Find its perimeter.`;a=`${2*x+2*y+8} cm.`;}if(mode==='samePerimeter5'){q=`Give different whole-number side lengths for another rectangle with perimeter ${total} cm.`;a=`Accept any pair adding to ${x+y}, other than ${x} and ${y}.`;}}
  else if(mode.startsWith('area')||mode==='sameArea5'){const rows=4+i%4,cols=6+i%5,total=rows*cols;model={type:'groups',groups:rows,size:cols,total};q=`Find the area of a rectangle ${rows} cm by ${cols} cm.`;a=`${total} cm².`;if(mode==='areaSquare5'){q=`Find the area of a square with side ${rows+2} cm.`;a=`${(rows+2)**2} cm².`;}if(mode==='areaEstimate5'){q=`An irregular shape covers ${total-3} full squares and about 6 half-squares. Estimate its area.`;a=`About ${total} square units.`;}if(mode==='sameArea5'){q=`Give two different rectangles with area ${total} cm² and compare their perimeters.`;a=`Accept two correct factor pairs and perimeters.`;}}
  else if(mode.startsWith('volume')){const x=2+i%4,y=3+i%3,z=4+i%2,total=x*y*z;model={type:'solid',name:'cuboid',rotated:i%2===0};q=`Find the volume of a cuboid ${x} cm × ${y} cm × ${z} cm.`;a=`${total} cm³.`;if(mode==='volumeEstimate5'){q=`Estimate how many 1 cm³ cubes fill a ${x} by ${y} by ${z} cuboid.`;}if(mode==='volumeMissing5'){q=`A cuboid has volume ${total} cm³, length ${x} cm and width ${y} cm. Find its height.`;a=`${z} cm.`;}}
  else if(mode==='moneyFourOps5'){const p=235+i*37,count=2+i,total=p*count;model={type:'money',a:p,b:p*(count-1),op:'+',total};q=`${count} books cost £${(p/100).toFixed(2)} each. Find the total.`;a=`£${(total/100).toFixed(2)}.`;}
  else {const a1=3+i,b1=250+i*25,total=a1*1000+b1;model={type:'convert',a:a1,b:b1,factor:1000,unit:'metres',big:'kilometres',total};q=`A route is ${a1} km ${b1} m. Write it in metres.`;a=`${total} m.`;}
 }
 else if(domains.shape.includes(mode)){
  const angle=[35,70,95,125,145][i%5];model={type:'angle',angle};q=`Estimate then measure an angle of ${angle}°. Classify it.`;a=`${angle}°; ${angle<90?'acute':'obtuse'}.`;
  if(mode==='angleDraw5'){q=`Draw an angle of ${angle}° accurately.`;a=`An accurately drawn ${angle}° angle.`;}
  if(mode==='angleFacts5'||mode==='angleNinety5'){const known=70+i*5,total=mode==='angleFacts5'?180:360;model={type:'numbers',values:[known,total-known,total]};q=`Angles total ${total}°. One angle is ${known}°. Find the missing angle.`;a=`${total-known}°.`;}
  if(mode==='solidFrom2D5'||mode==='classifyShapes5'){const names=['cube','cuboid','triangular prism','square-based pyramid'],name=names[i%4];model={type:'solid',name,rotated:i%2===0};q=`Identify the 3-D shape from its 2-D representation and state two properties.`;a=`${name}; accept two correct properties.`;}
  if(mode==='rectangleProperties5'){const x=6+i,y=4+i%4;model={type:'rectangle',a:x,b:y,total:2*(x+y)};q=`A rectangle has one side ${x} cm and perimeter ${2*(x+y)} cm. Find the other side and state its angle properties.`;a=`${y} cm; four right angles.`;}
  if(mode==='regularIrregular5'||mode==='shapeProblem5'){const regular=i%2===0,name=regular?'equilateral triangle':'trapezium';model={type:'polygon',name};q=`Is the shown ${name} regular or irregular? Explain from its sides and angles.`;a=`${regular?'Regular':'Irregular'}; ${regular?'all sides and angles are equal':'not all sides and angles are equal'}.`;}
 }
 else if(domains.coordinate.includes(mode)){
  const x=1+i%5,y=2+i%4,dx=2+i%3,dy=1+i%2;model={type:'coordinate',x,y,dx:mode==='translate5'||mode==='transformationDescribe5'||mode==='coordinateProblem5'?dx:0,dy:mode==='translate5'||mode==='transformationDescribe5'||mode==='coordinateProblem5'?dy:0};q=mode==='coordinatePlot5'?`Plot and label (${x}, ${y}).`:mode==='reflect5'?`Reflect (${x}, ${y}) in the vertical line x = 5.`:`Translate (${x}, ${y}) ${dx} right and ${dy} up.`;a=mode==='coordinatePlot5'?`(${x}, ${y}).`:mode==='reflect5'?`(${10-x}, ${y}).`:`(${x+dx}, ${y+dy}).`;if(mode==='reflect5')model={type:'coordinate',x,y,dx:10-2*x,dy:0};
 }
 else if(domains.data.includes(mode)){
  const key=[2,5,10][i%3],values=[3+i%3,5+i%3,4+i%3].map(v=>v*key);model={type:'data',mode:mode.startsWith('table')?'table':'line',labels:['Mon','Tue','Wed'],values,key};q=mode.includes('Compare')?`How many more were recorded on Tuesday than Monday?`:mode.includes('Sum')||mode.includes('Problem')?`Find the total for all three days.`:`Read the value for Tuesday.`;a=mode.includes('Compare')?`${values[1]-values[0]}.`:mode.includes('Sum')||mode.includes('Problem')?`${values.reduce((s,v)=>s+v,0)}.`:`${values[1]}.`;
 }
 else throw Error('Unhandled mode '+mode);
 challenge();return {q,a,answer:a,model,kind,mode,steps:guidance[kind]};
}

export function question(mode,index,level='expected'){return makeQuestion(mode,index,level)}
export function makeLesson(week,day){const [unit,titles,modes]=weeks[week-1],title=titles.split('|')[day-1],mode=modes.split('|')[day-1],examples=Array.from({length:5},(_,i)=>question(mode,i)),kind=examples[0].kind,term=week<=10?'Autumn':week<=20?'Spring':'Summer';return {year:5,week,day,term,title,slug:slugify(title),mode,character:'Pip',objective:'To '+title[0].toLowerCase()+title.slice(1)+'.',vocabulary:vocab[kind],prior:prior[kind],resources:'Place-value counters, fraction strips, squared paper, ruler, protractor, clocks, money, unit cubes or graph paper as appropriate.',successCriteria:['I can represent the mathematics accurately.','I can explain why my method works using precise vocabulary.','I can check my answer and apply the idea to a problem.'],misconception:misconceptions[kind],check:guidance[kind][3],warmup:prior[kind]+' Include mixed multiplication-table retrieval.',teacherModel:guidance[kind],guided:examples[1].q,independent:'Pause at each You do. Pupils attempt the question before the model and steps are revealed. Choose the appropriate worksheet.',plenary:examples[4].q,preteach:{focus:prior[kind],steps:guidance[kind].slice(0,3),questions:Array.from({length:3},(_,i)=>question(mode,i,'lower'))},lower:Array.from({length:5},(_,i)=>question(mode,i+5,'lower')),expected:Array.from({length:5},(_,i)=>question(mode,i+5)),higher:Array.from({length:5},(_,i)=>question(mode,i+5,'higher')),examples,curriculumSource:source};}

const root='.qa/year5-maths';await fs.mkdir(root,{recursive:true});const lessons=weeks.flatMap((_,w)=>Array.from({length:5},(_,d)=>makeLesson(w+1,d+1)));const curriculum=weeks.map(([unit,titles],w)=>({week:w+1,term:w<10?'Autumn':w<20?'Spring':'Summer',unit,days:titles.split('|')}));await fs.writeFile(root+'/lessons.json',JSON.stringify(lessons,null,2));await fs.writeFile(root+'/curriculum.json',JSON.stringify(curriculum,null,2));await fs.writeFile(root+'/curriculum-coverage.json',JSON.stringify({source,statutoryDomains:['number and place value','addition and subtraction','multiplication and division','fractions including decimals and percentages','measurement','geometry properties of shapes','geometry position and direction','statistics'],lessonCount:lessons.length,termEvaluations:['autumn','spring','summer'],statutoryCoverage:['numbers to 1,000,000 and Roman numerals to 1,000','formal multiplication by two digits and short division','primes factors squares cubes scaling and rates','mixed and improper fractions and related denominators','thousandths percentages and FDP equivalents','metric imperial time perimeter area and volume','angles 3-D representations regular and irregular polygons','coordinates reflection translation line graphs tables and timetables']},null,2));console.log('Prepared '+lessons.length+' statutory-aligned Year 5 lessons.');
