import fs from 'node:fs/promises';

export const source='https://www.gov.uk/government/publications/national-curriculum-in-england-mathematics-programmes-of-study/national-curriculum-in-england-mathematics-programmes-of-study#year-4-programme-of-study';

const weeks=[
['Place value to 10,000','Thousands hundreds tens and ones|Read and write four-digit numbers|Partition four-digit numbers|Find the value of each digit|One thousand more and less','place4|words4|partition4|digit4|thousandMore'],
['Compare order and represent numbers','Compare numbers beyond 1,000|Order four-digit numbers|Estimate on a number line|Count through zero|Read Roman numerals to 100','compare4|order4|line4|negative|roman'],
['Rounding and place-value reasoning','Round to the nearest 10|Round to the nearest 100|Round to the nearest 1,000|Choose a useful rounding point|Solve place-value problems','round10|round100|round1000|roundChoose|placeProblem'],
['Four-digit addition','Add without exchange|Exchange ones and tens|Add with several exchanges|Estimate and check a sum|Solve two-step addition problems','add4|add4One|add4Many|add4Check|add4Story'],
['Four-digit subtraction','Subtract without exchange|Exchange across one place|Exchange across more than one place|Estimate and check a difference|Solve two-step subtraction problems','sub4|sub4One|sub4Many|sub4Check|sub4Story'],
['Multiplication tables to 12 × 12','Six times table|Seven times table|Nine times table|Eleven times table|Twelve times table','times6|times7|times9|times11|times12'],
['Multiplicative reasoning','Use related division facts|Find factor pairs|Use commutativity|Multiply three numbers|Use the distributive law','divisionFacts4|factorPairs|commute|threeFactors|distributive'],
['Written multiplication','Multiply two digits by one digit|Multiply with an exchange|Multiply three digits by one digit|Use short multiplication|Solve multiplication problems','multiply2|multiply2Exchange|multiply3|multiply3Exchange|multiplyProblem4'],
['Division and correspondence','Divide two digits exactly|Divide three digits exactly|Use short division|Solve integer scaling problems|Solve correspondence problems','divide2|divide3|shortDivision|scale4|correspondence4'],
['Autumn consolidation','Place value review|Addition and subtraction review|Times-table review|Multiplication and division review|Autumn reasoning challenge','autumnPlace|autumnCalc|autumnTables|autumnMult|autumnReason'],
['Length and unit conversion','Convert kilometres and metres|Convert metres and centimetres|Convert centimetres and millimetres|Compare mixed lengths|Solve length conversion problems','kmM|mCm|cmMm|lengthCompare4|lengthProblem4'],
['Perimeter','Measure perimeter|Perimeter of rectangles|Perimeter of rectilinear shapes|Find a missing side|Solve perimeter problems','perimeterMeasure4|perimeterRectangle4|perimeterRectilinear4|perimeterMissing4|perimeterProblem4'],
['Area','Count squares for area|Compare areas|Make shapes with a given area|Connect arrays and area|Solve area problems','areaCount|areaCompare|areaMake|areaArray|areaProblem'],
['Equivalent fractions','Recognise equivalent fractions|Build equivalent fraction families|Use multiplication to find equivalents|Simplify using common factors|Explain fraction equivalence','equivRecognise4|equivFamily4|equivMultiply4|equivSimplify4|equivExplain4'],
['Fractions of quantities','Find a unit fraction of a quantity|Find a non-unit fraction|Divide a quantity using fractions|Find a fraction of a measure|Solve fraction-of-quantity problems','unitOf4|nonUnitOf4|fractionDivide4|fractionMeasure4|fractionProblem4'],
['Add and subtract fractions','Add fractions with the same denominator|Subtract fractions with the same denominator|Complete a whole|Calculate beyond one whole|Solve fraction calculation problems','fractionAdd4|fractionSub4|fractionWhole4|fractionBeyond4|fractionCalcProblem4'],
['Tenths hundredths and decimals','Make tenths|Make hundredths|Write decimal equivalents|Count in hundredths|Connect fractions and decimals','tenths4|hundredths4|decimalWrite4|hundredthsCount4|fractionDecimal4'],
['Decimal place value','Divide by 10|Divide by 100|Compare decimals to two places|Round one-place decimals|Solve decimal place-value problems','divide10|divide100|decimalCompare4|decimalRound4|decimalProblem4'],
['Money and decimal measures','Write money as decimals|Compare money amounts|Calculate with pounds and pence|Use decimals in measure|Solve money and measure problems','moneyDecimal4|moneyCompare4|moneyCalc4|decimalMeasure4|moneyMeasureProblem4'],
['Spring consolidation','Length and perimeter review|Area review|Fraction review|Decimal review|Spring reasoning challenge','springLength|springArea|springFraction|springDecimal|springReason'],
['Time and duration','Read analogue and digital time|Convert 12-hour and 24-hour time|Convert hours and minutes|Convert minutes and seconds|Solve duration problems','timeDigital4|time24Four|hoursMinutes4|minutesSeconds4|duration4'],
['Angles','Identify acute and obtuse angles|Compare angles with a right angle|Order angles by size|Recognise two right angles|Solve angle reasoning problems','acuteObtuse4|angleCompare4|angleOrder4|twoRightAngles4|angleReason4'],
['Triangles and quadrilaterals','Classify triangles|Compare triangle properties|Classify quadrilaterals|Compare quadrilateral properties|Solve shape classification problems','triangles4|triangleCompare4|quadrilaterals4|quadCompare4|shapeReason4'],
['Symmetry','Find vertical lines of symmetry|Find horizontal lines of symmetry|Find symmetry in different orientations|Complete a symmetric figure|Create and explain a symmetric pattern','symVertical4|symHorizontal4|symRotate4|symComplete4|symCreate4'],
['Coordinates','Read coordinates in the first quadrant|Plot coordinates|Complete a rectangle on a grid|Complete a polygon on a grid|Solve coordinate problems','coordRead4|coordPlot4|coordRectangle4|coordPolygon4|coordProblem4'],
['Translation','Translate left and right|Translate up and down|Describe a translation|Translate a polygon|Solve translation problems','translateLR4|translateUD4|translateDescribe4|translatePolygon4|translateProblem4'],
['Bar charts and pictograms','Read a scaled pictogram|Read a bar chart|Choose a suitable scale|Complete a bar chart|Solve comparison problems','pictogram4|bar4|scaleChart4|completeBar4|dataCompare4'],
['Tables and time graphs','Read a table|Read a time graph|Describe change over time|Solve sum and difference questions|Solve two-step data problems','table4|timeGraph4|changeGraph4|dataSum4|dataTwo4'],
['Arithmetic and problem solving','Choose an efficient mental method|Solve mixed written calculations|Solve two-step word problems|Check and explain an answer|Investigate a number pattern','efficient4|mixedCalc4|twoStep4|checkExplain4|pattern4'],
['Summer consolidation','Number and calculation review|Fractions and decimals review|Measure and time review|Geometry and statistics review|Ready for Year Five','summerNumber|summerFraction|summerMeasure|summerGeometry|summerFinal']
];

const domainFor=mode=>{const m=mode.toLowerCase();return m.includes('fraction')||m.includes('equiv')||m.includes('tenths')||m.includes('hundredths')||m.startsWith('unitof')||m.startsWith('nonunitof')||m.includes('decimal')||m.includes('divide10')||m.includes('divide100')?'fraction':m.includes('time')||m.includes('hours')||m.includes('minutes')||m.includes('duration')?'time':m.includes('angle')||m.includes('acute')||m.includes('obtuse')||m.includes('triangle')||m.includes('quad')||m.includes('sym')||m.includes('coord')||m.includes('translate')||m.includes('shape')?'shape':m.includes('chart')||m.includes('data')||m.includes('graph')||m==='table4'||m.includes('pictogram')||m.includes('bar')?'data':m.includes('length')||m.includes('perimeter')||m.includes('area')||['kmm','mcm','cmmm'].includes(m)?'measure':m.includes('money')?'money':m.includes('multiply')||m.includes('times')||m.includes('factor')||m.includes('commute')||m.includes('distributive')||m.includes('scale4')||m.includes('threefactors')?'multiply':m.includes('divide')||m.includes('division')||m.includes('correspondence')?'divide':m.includes('add')||m.includes('sub')||m.includes('calc')||m.includes('twostep')||m.includes('efficient')||m.includes('check')?'calc':'place';};

const vocab={place:['thousands','hundreds','tens','ones','round'],calc:['sum','difference','exchange','inverse','estimate'],multiply:['factor','multiple','product','commutative','distributive'],divide:['dividend','divisor','quotient','exact','inverse'],fraction:['whole','numerator','denominator','equivalent','hundredth'],measure:['convert','kilometre','metre','centimetre','perimeter','area'],money:['pounds','pence','decimal','change'],time:['analogue','digital','duration','12-hour','24-hour'],shape:['acute','obtuse','triangle','quadrilateral','symmetry','coordinate','translation'],data:['scale','interval','discrete','continuous','difference']};
const prior={place:'Recall three-digit place value and count in hundreds.',calc:'Align place-value columns and recall addition and subtraction facts.',multiply:'Recall the 2, 3, 4, 5, 8 and 10 multiplication tables.',divide:'Connect equal groups with multiplication and division facts.',fraction:'Recognise equal parts and fractions on a number line.',measure:'Choose a suitable unit and measure accurately.',money:'Recall that 100 pence equals one pound.',time:'Read analogue time to the minute.',shape:'Recognise right angles, parallel lines and familiar shapes.',data:'Read a key, category and simple scale.'};
const guidance={place:['Build the number with place-value counters.','Name each digit and its value.','Move, compare or round using the marked boundary.','Read the result and check every place.'],calc:['Estimate before calculating.','Align thousands, hundreds, tens and ones.','Calculate one column at a time and record each exchange.','Check with the inverse and compare with the estimate.'],multiply:['Show equal groups or partition the larger factor.','Use a known table fact for each part.','Combine the partial products carefully.','Check with division or a second method.'],divide:['Identify the dividend and divisor.','Partition or share into equal groups.','Record each quotient digit in its correct place.','Multiply the quotient by the divisor to check.'],fraction:['Identify the whole and equal parts.','Use the denominator to set the part size.','Use the numerator to count, combine or compare parts.','Check the fraction or decimal against the model.'],measure:['Write the conversion fact first.','Convert both quantities to the same unit.','Calculate with the numbers, then restore the unit.','Estimate with the diagram or measuring tool.'],money:['Write pounds and pence with two decimal places.','Convert to pence when that makes the calculation clearer.','Calculate and record the money symbol.','Check that costs and change balance.'],time:['Read the hour and minute information separately.','Convert both times or durations to the same unit.','Use a timeline when crossing an hour.','Check am, pm and the units.'],shape:['Mark the properties that can be tested.','Use a ruler, right-angle checker or grid.','Classify or move the figure from its properties.','Explain using precise mathematical vocabulary.'],data:['Read the title, labels and scale.','Find the value of every interval or symbol.','Select the required values and calculate.','Check the answer against the graph or table.']};
const misconceptions={place:'A pupil reads 4,072 as 472. Use the zero placeholder to explain the difference.',calc:'A pupil exchanges but does not adjust the next column. Show both changes.',multiply:'A pupil uses a nearby multiplication fact without adjusting. Show the missing step.',divide:'A pupil writes a quotient digit in the wrong place. Link each digit to its value.',fraction:'A pupil changes the denominator when adding equal parts. Explain why the part size stays fixed.',measure:'A pupil combines different units before converting. Put both measures in one unit first.',money:'A pupil writes £3.5 instead of £3.05. Explain the two decimal places.',time:'A pupil treats 1.45 hours as 1 hour 45 minutes. Explain why time is not base ten.',shape:'A pupil classifies a shape by its appearance. Rotate it and test its properties.',data:'A pupil counts gridlines rather than intervals. Mark one complete interval.'};

const reviewModes={autumnPlace:['place4','compare4','round100','negative','roman'],autumnCalc:['add4Many','sub4Many','add4Check','sub4Check','twoStep4'],autumnTables:['times6','times7','times9','times11','times12'],autumnMult:['factorPairs','multiply3','divide3','scale4','correspondence4'],autumnReason:['placeProblem','add4Story','distributive','shortDivision','roundChoose'],springLength:['kmM','mCm','perimeterRectangle4','perimeterMissing4','lengthProblem4'],springArea:['areaCount','areaCompare','areaMake','areaArray','areaProblem'],springFraction:['equivFamily4','nonUnitOf4','fractionAdd4','fractionBeyond4','fractionProblem4'],springDecimal:['hundredths4','divide10','divide100','decimalCompare4','decimalRound4'],springReason:['perimeterProblem4','equivExplain4','fractionCalcProblem4','moneyMeasureProblem4','decimalProblem4'],summerNumber:['place4','add4Many','sub4Many','times12','shortDivision'],summerFraction:['equivSimplify4','fractionProblem4','fractionBeyond4','decimalCompare4','moneyDecimal4'],summerMeasure:['lengthProblem4','perimeterProblem4','areaProblem','time24Four','duration4'],summerGeometry:['angleOrder4','quadrilaterals4','symComplete4','coordPolygon4','dataCompare4'],summerFinal:['twoStep4','pattern4','dataTwo4','shapeReason4','checkExplain4']};
const roman=n=>{const map=[[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let s='';for(const [v,c] of map)while(n>=v){s+=c;n-=v;}return s;};
const words=n=>{const ones=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];const tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];if(n<20)return ones[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?'-'+ones[n%10]:'');if(n<1000)return ones[Math.floor(n/100)]+' hundred'+(n%100?' and '+words(n%100):'');return ones[Math.floor(n/1000)]+' thousand'+(n%100?' '+words(n%100):n%1000?' '+words(n%1000):'');};

function baseQuestion(mode,index,level){
 const i=index%10,low=level==='lower',hard=level==='higher';let q='',a='',model={},kind=domainFor(mode);const addChallenge=()=>{if(low)q+=' Use the model to help.';if(hard){q+=' Explain how you checked.';a+=' Accept a correct check or explanation.';}};
 if(['place4','words4','partition4','digit4','thousandMore','compare4','order4','line4','negative','roman','round10','round100','round1000','roundChoose','placeProblem','pattern4'].includes(mode)){
  const n=(low?1200:3400)+i*217+46;kind='place';model={type:'place',n};q=`Partition ${n} into thousands, hundreds, tens and ones.`;a=`${Math.floor(n/1000)} thousands, ${Math.floor(n/100)%10} hundreds, ${Math.floor(n/10)%10} tens and ${n%10} ones.`;
  if(mode==='words4'){q=`Write ${n} in words.`;a=words(n)+'.';}
  if(mode==='partition4'){q=`Complete: ${n} = ${Math.floor(n/1000)*1000} + ___ + ${Math.floor(n/10)%10*10} + ${n%10}.`;a=`${Math.floor(n/100)%10*100}.`;}
  if(mode==='digit4'){const d=[1000,100,10,1][i%4],digit=Math.floor(n/d)%10;q=`What is the value of the digit ${digit} in ${n}?`;a=`${digit*d}.`;}
  if(mode==='thousandMore'){model={type:'moreLess',values:[n-1000,n,n+1000],delta:1000};q=`Find 1,000 more and 1,000 less than ${n}.`;a=`${n+1000} and ${n-1000}.`;}
  if(mode==='compare4'||mode==='order4'){const values=[n,n+90,n-105];model={type:'numbers',values};q=mode==='order4'?`Order ${values.join(', ')} from smallest.`:`Write <, > or =: ${values[0]} ___ ${values[1]}.`;a=mode==='order4'?[...values].sort((x,y)=>x-y).join(', ')+'.':'<.';}
  if(mode==='line4'){const start=Math.floor(n/1000)*1000,value=start+(i%9+1)*100;model={type:'numberline',start,end:start+1000,value,step:100};q='Read the marked point on the number line.';a=value+'.';}
  if(mode==='negative'){const value=-5+i,start=-10,end=10;model={type:'numberline',start,end,value,step:2};q=`A temperature is ${Math.abs(value)} degrees ${value<0?'below':'above'} zero. Write it as an integer.`;a=`${value}.`;}
  if(mode==='roman'){const value=11+i*7;model={type:'sequence',values:[roman(value-1),roman(value),roman(value+1)],missing:1};q=`Write ${value} in Roman numerals.`;a=roman(value)+'.';}
  if(mode.startsWith('round')){const unit=mode==='round10'?10:mode==='round100'?100:mode==='round1000'?1000: i%2?100:1000;const rounded=Math.round(n/unit)*unit;model={type:'numberline',start:Math.floor(n/unit)*unit,end:Math.floor(n/unit)*unit+unit,value:n,step:unit/10};q=`Round ${n} to the nearest ${unit.toLocaleString('en-GB')}.`;a=`${rounded}.`;}
  if(mode==='placeProblem'){const x=n+1000-100;q=`Start at ${n}, add 1,000 and subtract 100. Where do you finish?`;a=`${x}.`;model={type:'moreLess',values:[n,n+1000,x],delta:1000};}
  if(mode==='pattern4'){const start=125+i*10,step=[25,50,100][i%3],values=Array.from({length:5},(_,j)=>start+j*step);model={type:'sequence',values,missing:3};q=`Continue the pattern: ${values.slice(0,3).join(', ')}, ___, ${values[4]}.`;a=`${values[3]}. The rule is add ${step}.`;}
 }
 else if(mode.startsWith('add4')||mode.startsWith('sub4')||['efficient4','mixedCalc4','twoStep4','checkExplain4'].includes(mode)){
  kind='calc';let x=(low?2100:4300)+i*131+27,y=(low?320:1700)+i*67+14,op=mode.startsWith('sub')?'−':'+';if(op==='−'&&y>x)[x,y]=[y,x];let total=op==='+'?x+y:x-y;model={type:'calculation',a:x,b:y,op,total};q=`Calculate ${x} ${op} ${y}.`;a=`${total}.`;
  if(mode.includes('Check')){q=`Estimate, calculate and check ${x} ${op} ${y}.`;a=`${total}. A suitable estimate and inverse check should agree.`;}
  if(mode.includes('Story')||mode==='twoStep4'){const z=110+i*9;model={type:'twoStep',a:x,b:y,c:z,total:x+y-z};q=`A museum recorded ${x} visitors, then ${y} more arrived and ${z} left. How many remained?`;a=`${x+y-z}. First add, then subtract ${z}.`;}
  if(mode==='efficient4'){x=1998+i*100;y=48+i;total=x+y;model={type:'compensate',a:x,b:y,total};q=`Calculate ${x} + ${y} efficiently by adjusting ${x}.`;a=`${total}. Add ${x+2}, then subtract 2.`;}
  if(mode==='mixedCalc4'){op=i%2?'−':'+';x=5270+i*71;y=1834+i*29;total=op==='+'?x+y:x-y;model={type:'calculation',a:x,b:y,op,total};q=`Calculate ${x} ${op} ${y}.`;a=`${total}.`;}
  if(mode==='checkExplain4'){q=`Is ${x} + ${y} = ${x+y} reasonable? Show an estimate and an inverse check.`;a=`Yes. The estimate is close and ${x+y} − ${y} = ${x}.`;model={type:'estimate',a:x,b:y,total:Math.round(x/100)*100+Math.round(y/100)*100};}
 }
 else if(mode.startsWith('times')||['divisionFacts4','factorPairs','commute','threeFactors','distributive','multiply2','multiply2Exchange','multiply3','multiply3Exchange','multiplyProblem4','divide2','divide3','shortDivision','scale4','correspondence4'].includes(mode)){
  const table=Number(mode.replace('times',''))||[6,7,9,11,12][i%5];kind=mode.startsWith('divide')||mode==='shortDivision'||mode==='divisionFacts4'?'divide':'multiply';let x=2+i%11,y=table,total=x*y;model={type:'groups',groups:x,size:y,total};q=`Calculate ${x} × ${y}.`;a=`${total}.`;
  if(mode==='divisionFacts4'){const d=[6,7,9,11,12][i%5],quot=2+i%10;model={type:'division',a:d*quot,b:d,total:quot,remainder:0};q=`Use ${d} × ${quot} = ${d*quot} to find ${d*quot} ÷ ${d}.`;a=`${quot}.`;}
  if(mode==='factorPairs'){const n=[12,18,24,30,36,40,42,48,54,60][i];const pairs=[];for(let d=1;d<=Math.sqrt(n);d++)if(n%d===0)pairs.push(`${d} × ${n/d}`);model={type:'groups',groups:n<=30?Math.floor(n/2):6,size:n<=30?2:Math.floor(n/6),total:n};q=`Find every factor pair of ${n}.`;a=pairs.join(', ')+'.';}
  if(mode==='commute'){model={type:'groups',groups:x,size:y,total};q=`Complete and explain: ${x} × ${y} = ${y} × ___.`;a=`${x}. Multiplication is commutative.`;}
  if(mode==='threeFactors'){const z=2+i%3;x=2+i%4;y=3+i%3;total=x*y*z;model={type:'groups',groups:x*y,size:z,total};q=`Calculate ${x} × ${y} × ${z}. Choose an efficient order.`;a=`${total}.`;}
  if(mode==='distributive'){x=21+i;y=3+i%4;total=x*y;model={type:'multiply',a:x,b:y,total};q=`Partition ${x} to calculate ${x} × ${y}.`;a=`${Math.floor(x/10)*10} × ${y} + ${x%10} × ${y} = ${total}.`;}
  if(mode.startsWith('multiply')){x=(mode.includes('3')?123:24)+i*(mode.includes('3')?17:3);y=3+i%6;total=x*y;model={type:'multiply',a:x,b:y,total};q=mode==='multiplyProblem4'?`${y} trays hold ${x} counters each. How many counters altogether?`:`Calculate ${x} × ${y} using a formal written method.`;a=`${total}${mode==='multiplyProblem4'?' counters':''}.`;}
  if(['divide2','divide3','shortDivision'].includes(mode)){const d=3+i%6,quot=(mode==='divide2'?12:mode==='divide3'?102:42)+i;total=d*quot;model={type:'division',a:total,b:d,total:quot,remainder:0};q=`Calculate ${total} ÷ ${d}.`;a=`${quot}.`;}
  if(mode==='scale4'){x=14+i;y=3+i%4;total=x*y;model={type:'multiply',a:x,b:y,total};q=`A rope is ${x} cm. Another is ${y} times as long. How long is it?`;a=`${total} cm.`;}
  if(mode==='correspondence4'){x=2+i%4;y=3+i%4;model={type:'groups',groups:x,size:y,total:x*y};q=`There are ${x} tops and ${y} trousers. How many different outfits?`;a=`${x*y} outfits.`;}
 }
 else if(['kmM','mCm','cmMm','lengthCompare4','lengthProblem4','perimeterMeasure4','perimeterRectangle4','perimeterRectilinear4','perimeterMissing4','perimeterProblem4','areaCount','areaCompare','areaMake','areaArray','areaProblem'].includes(mode)){
  kind='measure';if(['kmM','mCm','cmMm'].includes(mode)){const map={kmM:[1000,'metres','kilometres'],mCm:[100,'centimetres','metres'],cmMm:[10,'millimetres','centimetres']},[factor,unit,big]=map[mode],x=2+i%6,b=i%4*factor/10,total=x*factor+b;model={type:'convert',a:x,b,factor,unit,big,total};q=`Convert ${x} ${big}${b?' and '+b+' '+unit:''} to ${unit}.`;a=`${total} ${unit}.`;}
  else if(mode.startsWith('length')){const a1=2+i%5,b1=250+i*30,total=a1*1000+b1;model={type:'convert',a:a1,b:b1,factor:1000,unit:'metres',big:'kilometres',total};q=mode==='lengthCompare4'?`Which is longer: ${a1} km or ${b1+1800} m?`:`A route is ${a1} km and ${b1} m. How many metres is that?`;a=mode==='lengthCompare4'?`${Math.max(a1*1000,b1+1800)} m is longer.`:`${total} m.`;}
  else if(mode.startsWith('perimeter')){const x=5+i,y=3+i%6,total=2*(x+y);model={type:'rectangle',a:x,b:y,total,missing:mode==='perimeterMissing4'};q=mode==='perimeterMissing4'?`A rectangle has perimeter ${total} cm and length ${x} cm. Find its width.`:`Find the perimeter of a rectangle measuring ${x} cm by ${y} cm.`;a=mode==='perimeterMissing4'?`${y} cm.`:`${total} cm.`;}
  else {const rows=3+i%4,cols=4+i%5,total=rows*cols;model={type:'groups',groups:rows,size:cols,total};q=mode==='areaMake'?`Draw a rectilinear shape with area ${total} square centimetres.`:mode==='areaCompare'?`A ${rows} by ${cols} rectangle and a 2 by ${Math.ceil(total/2)} rectangle are shown. Which has the greater area?`:`Find the area of a ${rows} by ${cols} rectangle by counting squares.`;a=mode==='areaMake'?`Any correct shape covering ${total} unit squares.`:mode==='areaCompare'?`${2*Math.ceil(total/2)>total?'The second rectangle':'They have equal area'}.`:`${total} square centimetres.`;}
 }
 else if(kind==='fraction'||kind==='money'){
  const den=[4,5,8,10,100][i%5],num=1+i%Math.max(1,den-1);model={type:'fraction',num,den};q=`Represent ${num}/${den}.`;a=`${num}/${den}.`;
  if(mode.startsWith('equiv')){const d=[2,3,4,5][i%4],n=1+i%(d-1),factor=2+i%3;model={type:'equivalent',num:n,den:d,factor};q=`Complete: ${n}/${d} = ___/${d*factor}.`;a=`${n*factor}/${d*factor}.`;if(mode==='equivSimplify4'){q=`Simplify ${n*factor}/${d*factor}.`;a=`${n}/${d}.`;}}
  if(['unitOf4','nonUnitOf4','fractionDivide4','fractionMeasure4','fractionProblem4'].includes(mode)){const d=[2,3,4,5,8][i%5],n=mode==='unitOf4'?1:1+i%(d-1),total=d*(5+i),value=total*n/d;model={type:'fractionOf',num:n,den:d,total,value,reverse:false};q=`Find ${n}/${d} of ${total}${mode==='fractionMeasure4'?' cm':''}.`;a=`${value}${mode==='fractionMeasure4'?' cm':''}.`;}
  if(mode.startsWith('fractionAdd')||mode.startsWith('fractionSub')||mode.startsWith('fractionWhole')||mode.startsWith('fractionBeyond')||mode.startsWith('fractionCalc')){const d=5+i%4,n=1+i%3,other=mode.startsWith('fractionSub')?1:2,value=mode.startsWith('fractionSub')?n+other-other:n+other;const op=mode.startsWith('fractionSub')?'−':'+';model={type:'fractionCalc',num:op==='−'?n+other:n,other,den:d,op,value};q=`Calculate ${model.num}/${d} ${op} ${other}/${d}.`;a=`${value}/${d}.`;}
  if(['tenths4','hundredths4','decimalWrite4','hundredthsCount4','fractionDecimal4','divide10','divide100','decimalCompare4','decimalRound4','decimalProblem4'].includes(mode)){const divisor=mode==='divide100'?100:10,n=12+i*3,value=n/divisor;model={type:'numberline',start:0,end:mode==='divide100'?1:5,value,step:mode==='divide100'?.1:.5};q=`Calculate ${n} ÷ ${divisor}.`;a=`${value}.`;if(mode==='decimalCompare4'){const b=value+.05;q=`Write <, > or =: ${value.toFixed(2)} ___ ${b.toFixed(2)}.`;a='<.';model={type:'numbers',values:[value,b]};}if(mode==='decimalRound4'){const v=1.2+i*.1;q=`Round ${v.toFixed(1)} to the nearest whole number.`;a=`${Math.round(v)}.`;model={type:'numberline',start:1,end:3,value:v,step:.1};}if(['tenths4','hundredths4','decimalWrite4','hundredthsCount4','fractionDecimal4'].includes(mode)){const d=mode==='tenths4'?10:100,n=1+i%(d-1);model={type:'fractionLine',num:n,den:d,max:1};q=`Write ${n}/${d} as a decimal.`;a=`${(n/d).toFixed(d===10?1:2)}.`;}}
  if(kind==='money'){const p=235+i*37,qv=110+i*19,total=p+qv;model={type:'money',a:p,b:qv,op:'+',total};q=`Add £${(p/100).toFixed(2)} and £${(qv/100).toFixed(2)}.`;a=`£${(total/100).toFixed(2)}.`;if(mode==='moneyCompare4'){q=`Which is greater: £${(p/100).toFixed(2)} or £${(qv/100).toFixed(2)}?`;a=`£${(Math.max(p,qv)/100).toFixed(2)}.`;}if(mode==='moneyDecimal4'){q=`Write ${p}p in pounds.`;a=`£${(p/100).toFixed(2)}.`;model.read=true;}}
 }
 else if(kind==='time'){
  const hour=8+i%9,minute=(i*5)%60;model={type:'clock',hour,minute};q=`Write ${hour}:${String(minute).padStart(2,'0')} in words.`;a=`${minute===0?hour+' o’clock':minute+' minutes past '+hour}.`;if(mode==='time24Four'){const pm=hour<12?hour+12:hour;q=`Write ${hour}:${String(minute).padStart(2,'0')} pm using the 24-hour clock.`;a=`${pm}:${String(minute).padStart(2,'0')}.`;model.hour=pm;}if(mode==='hoursMinutes4'||mode==='minutesSeconds4'){const factor=60,x=2+i%5;model={type:'convert',a:x,b:0,factor,unit:mode==='hoursMinutes4'?'minutes':'seconds',big:mode==='hoursMinutes4'?'hours':'minutes',total:x*factor};q=`Convert ${x} ${model.big} to ${model.unit}.`;a=`${x*factor} ${model.unit}.`;}if(mode==='duration4'){const add=25+i*3,end=hour*60+minute+add;model.add=add;q=`A film starts at ${hour}:${String(minute).padStart(2,'0')} and ends at ${Math.floor(end/60)}:${String(end%60).padStart(2,'0')}. How long is it?`;a=`${add} minutes.`;}
 }
 else if(kind==='shape'){
  if(mode.startsWith('angle')||mode.includes('RightAngles')||mode==='acuteObtuse4'){const angle=[45,90,120,160][i%4];model={type:'angle',angle};q='Classify the angle as acute, right or obtuse.';a=`${angle<90?'Acute':angle===90?'Right':'Obtuse'} angle.`;}
  else if(mode.includes('triangle')||mode.includes('quad')||mode==='shapeReason4'){const names=['equilateral triangle','isosceles triangle','scalene triangle','rectangle','rhombus','trapezium'],name=names[i%names.length];model={type:'polygon',name};q=`Name or classify the ${name}. State two defining properties.`;a=`${name}. Accept two correct properties.`;}
  else if(mode.startsWith('coord')||mode.startsWith('translate')){const x=1+i%5,y=2+i%4,dx=2+i%3,dy=1+i%2;model={type:'coordinate',x,y,dx:mode.startsWith('translate')?dx:0,dy:mode.startsWith('translate')?dy:0};q=mode.startsWith('translate')?`Translate point (${x}, ${y}) ${dx} right and ${dy} up.`:`Plot and label the point (${x}, ${y}) in the first quadrant.`;a=mode.startsWith('translate')?`(${x+dx}, ${y+dy}).`:`Point (${x}, ${y}).`;}
  else {model={type:'symmetry',axis:mode==='symHorizontal4'?'horizontal':'vertical',complete:mode==='symComplete4'||mode==='symCreate4'};q='Identify or complete the line of symmetry.';a='A correct mirror image, equally spaced from the line.';}
 }
 else if(kind==='data'){
  const key=[2,5,10][i%3],values=[3+i%3,5+i%3,4+i%3].map(v=>v*key);model={type:'data',mode:mode==='table4'?'table':mode.includes('pictogram')?'pictogram':mode==='completeBar4'?'drawBar':'bar',labels:['A','B','C'],values,key};q=mode.includes('Compare')||mode.includes('Sum')||mode.includes('Two')?`How many more are in A and C altogether than in B?`:`How many are in category B?`;a=mode.includes('Compare')||mode.includes('Sum')||mode.includes('Two')?`${values[0]+values[2]-values[1]}.`:`${values[1]}.`;
 }
 else {throw Error('Unhandled '+mode);}
 addChallenge();return {q,a,answer:a,model,kind,mode,steps:guidance[kind]};
}

export function question(mode,index,level='expected'){if(reviewModes[mode])return baseQuestion(reviewModes[mode][index%5],index,level);return baseQuestion(mode,index,level);}
export function makeLesson(week,day){const [unit,titles,modes]=weeks[week-1],title=titles.split('|')[day-1],mode=modes.split('|')[day-1],examples=Array.from({length:5},(_,i)=>question(mode,i)),kind=examples[0].kind,term=week<=10?'Autumn':week<=20?'Spring':'Summer';return {year:4,week,day,term,title,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),mode,character:'Pip',objective:'To '+title[0].toLowerCase()+title.slice(1)+'.',vocabulary:vocab[kind],prior:prior[kind],resources:'Place-value counters, base-ten equipment, fraction strips, squared paper, ruler, clock, coins or shape models as appropriate.',successCriteria:['I can represent the mathematics accurately.','I can explain each step using the model and correct vocabulary.','I can check my answer and justify whether it is reasonable.'],misconception:misconceptions[kind],check:guidance[kind][3],warmup:prior[kind]+' Include a short multiplication-table retrieval question.',teacherModel:guidance[kind],guided:examples[1].q,independent:'Pause at each You do. Pupils attempt the question before the model and steps are revealed. Choose the appropriate worksheet.',plenary:examples[4].q,preteach:{focus:prior[kind],steps:guidance[kind].slice(0,3),questions:Array.from({length:3},(_,i)=>question(mode,i,'lower'))},lower:Array.from({length:5},(_,i)=>question(mode,i+5,'lower')),expected:Array.from({length:5},(_,i)=>question(mode,i+5)),higher:Array.from({length:5},(_,i)=>question(mode,i+5,'higher')),examples,curriculumSource:source};}

const root='.qa/year4-maths';await fs.mkdir(root,{recursive:true});const rawLessons=weeks.flatMap((_,w)=>Array.from({length:5},(_,d)=>makeLesson(w+1,d+1)));const lessons=JSON.parse(JSON.stringify(rawLessons).replaceAll('\u00c3\u2014','\u00d7'));await fs.writeFile(root+'/lessons.json',JSON.stringify(lessons,null,2));await fs.writeFile(root+'/curriculum.json',JSON.stringify(weeks.map(([unit,titles],w)=>({week:w+1,term:w<10?'Autumn':w<20?'Spring':'Summer',unit,days:titles.split('|')})),null,2));await fs.writeFile(root+'/curriculum-coverage.json',JSON.stringify({source,statutoryDomains:['number and place value','addition and subtraction','multiplication and division','fractions including decimals','measurement','geometry properties of shapes','geometry position and direction','statistics'],lessonCount:lessons.length,termEvaluations:['autumn','spring','summer'],multiplicationTables:'Daily retrieval plus explicit teaching of 6, 7, 9, 11 and 12 tables; facts to 12 × 12 used across all terms.'},null,2));console.log('Prepared '+lessons.length+' Year 4 lessons.');
