import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { LanguageService } from '../../core/services/language.service';
import { RetrievalStarterComponent } from './retrieval-starter.component';

interface CurriculumWeek { week:number; term:'Autumn'|'Spring'|'Summer'; unit:string; days:string[]; }

@Component({
  selector:'bp-year5-maths-lesson', standalone:true, imports:[RouterLink,FormsModule,RetrievalStarterComponent], changeDetection:ChangeDetectionStrategy.OnPush,
  template:`
    @if (title()) {
      <header class="bp-page-hero"><div class="bp-container"><a class="back" [routerLink]="l('/curriculum/maths/year/5')">← Year 5 curriculum map</a><span class="bp-chip">Year 5 Maths · {{ term() }} · Week {{ week }} · Day {{ day() }}</span><h1>{{ title() }}</h1><p>Develop secure Year 5 understanding through representation, fluency, reasoning and application.</p></div></header>
      <main class="bp-section"><div class="bp-container lesson-layout">
        <section class="plan bp-card"><div class="section-head"><div><span class="bp-label">Teacher planning</span><h2>Lesson focus and preparation</h2></div><button class="bp-btn" type="button" (click)="saveDraft()">Save notes</button></div><p class="hint">Use these notes to adapt the lesson for your class.</p><div class="field-grid"><label>Teacher / class<input [(ngModel)]="draft.teacher" /></label><label>Date<input type="date" [(ngModel)]="draft.date" /></label></div><label>Pre-teach, SEND and EAL support<textarea rows="3" [(ngModel)]="draft.support"></textarea></label><label>Assessment notes and next steps<textarea rows="4" [(ngModel)]="draft.assessment"></textarea></label>@if(saved()){<p class="saved">✓ Saved on this device</p>}</section>
        <aside class="overview bp-card"><span class="bp-label">Teaching point</span><h2>{{ unit() }}</h2><p>{{ teachingPoint() }}</p><h3>Key vocabulary</h3><p>{{ vocabulary() }}</p><h3>Watch for</h3><p>Pupils applying a remembered rule without checking whether it fits the representation or context.</p></aside>
        <bp-retrieval-starter [year]="5" [week]="week" [day]="day()" />
        <section class="sequence"><span class="bp-label">60-minute teaching sequence</span><h2>Lesson at a glance</h2><div class="sequence-grid"><article class="bp-card"><b>1 · Revisit</b><p>Complete the five retrieval questions and discuss efficient strategies.</p><small>5 minutes</small></article><article class="bp-card"><b>2 · Model</b><p>Represent {{ unit().toLowerCase() }} clearly. Think aloud, connect each step and model one common error.</p><small>15 minutes</small></article><article class="bp-card"><b>3 · Guided practice</b><p>Solve examples together. Ask pupils to justify choices using the model and precise vocabulary.</p><small>15 minutes</small></article><article class="bp-card"><b>4 · Independent</b><p>Move from fluency to reasoning and one contextual problem. Check methods, not only answers.</p><small>20 minutes</small></article><article class="bp-card"><b>5 · Review</b><p>Compare two strategies and complete one exit question linked to the lesson focus.</p><small>5 minutes</small></article></div></section>
        <section class="practice"><span class="bp-label">Differentiated practice</span><h2>Questions to use or adapt</h2><div class="practice-grid"><article class="bp-card"><b>Lower support</b><p>Use a worked example and concrete or pictorial model. Complete three carefully scaffolded examples.</p></article><article class="bp-card"><b>Expected</b><p>Complete five varied questions, including one explanation and one problem in context.</p></article><article class="bp-card"><b>Higher challenge</b><p>Find more than one method, test a statement and explain why the reasoning is always, sometimes or never true.</p></article></div></section>
        <aside class="preteach bp-card"><div><span class="bp-label">Before the lesson</span><h2>Pre-teach focus</h2><p>Revisit the vocabulary and prerequisite fact pupils need for {{ unit().toLowerCase() }}.</p></div><ul><li>✓ Use one clear representation</li><li>✓ Rehearse a complete spoken sentence</li><li>✓ Check one example independently</li></ul></aside>
      </div></main>
    } @else {<div class="bp-loading"><span class="bp-spinner"></span>Loading Year 5 lesson…</div>}
  `,
  styles:[`.back{display:block;width:max-content;margin-bottom:1rem;font-weight:700}.lesson-layout{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(320px,.95fr);gap:1.5rem}.plan,.overview,.preteach{padding:clamp(1.2rem,3vw,2rem)}.section-head{display:flex;align-items:start;justify-content:space-between;gap:1rem}.section-head h2,.overview h2{margin:.3rem 0}.hint,.overview p{color:var(--text-muted)}label{display:block;margin-top:.85rem;font-size:.82rem;font-weight:750}label input,label textarea{margin-top:.3rem;font-weight:400}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.saved{color:var(--accent-emerald);font-weight:800}.overview{border-top:6px solid var(--accent-sky)}.overview h3{margin:1rem 0 .2rem;font-size:.9rem}.sequence,.practice,.preteach{grid-column:1/-1}.sequence h2,.practice h2{margin:.35rem 0 1rem}.sequence-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.8rem}.sequence-grid article,.practice-grid article{display:flex;flex-direction:column;padding:1rem}.sequence-grid p,.practice-grid p{flex:1;color:var(--slate-600);font-size:.88rem}.sequence-grid small{color:var(--brand-d);font-weight:800}.practice-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.practice-grid article:first-child{border-top:5px solid var(--accent-amber)}.practice-grid article:nth-child(2){border-top:5px solid var(--accent-sky)}.practice-grid article:last-child{border-top:5px solid var(--accent-emerald)}.preteach{display:grid;grid-template-columns:1fr 1fr;gap:2rem;background:linear-gradient(135deg,var(--brand-tint),var(--white))}.preteach li{margin:.45rem 0}@media(max-width:950px){.lesson-layout,.sequence-grid{grid-template-columns:1fr}.plan,.overview,.sequence,.practice,.preteach{grid-column:1}.practice-grid{grid-template-columns:1fr}}@media(max-width:560px){.field-grid,.preteach{grid-template-columns:1fr}.section-head{display:block}.section-head .bp-btn{margin-top:.6rem;width:100%;justify-content:center}}`]
})
export class Year5MathsLessonComponent {
  private http=inject(HttpClient); private route=inject(ActivatedRoute); private lang=inject(LanguageService);
  readonly week=Number((this.route.snapshot.paramMap.get('week')??'week-1').replace('week-','')); readonly slug=this.route.snapshot.paramMap.get('slug')??''; readonly plan=signal<CurriculumWeek[]>([]); readonly saved=signal(false);
  readonly weekData=computed(()=>this.plan().find(item=>item.week===this.week)); readonly day=computed(()=>Math.max(1,(this.weekData()?.days.findIndex(item=>this.slugify(item)===this.slug)??0)+1)); readonly title=computed(()=>this.weekData()?.days[this.day()-1]??''); readonly unit=computed(()=>this.weekData()?.unit??'Year 5 mathematics'); readonly term=computed(()=>this.weekData()?.term??(this.week<=10?'Autumn':this.week<=20?'Spring':'Summer'));
  readonly teachingPoint=computed(()=>{const lead=this.title().split(':')[0];return `${lead}: connect the mathematical structure to an efficient method, then explain why the method works.`}); readonly vocabulary=computed(()=>this.unit().split(/—|,| and /).map(value=>value.trim()).filter(Boolean).join(' · '));
  draft={teacher:'',date:'',support:'',assessment:''};
  constructor(){this.http.get<CurriculumWeek[]>('/curriculum-plans/maths/year-5.json').subscribe(items=>{this.plan.set(items);this.loadDraft()})}
  l(path:string):string{return this.lang.localise(path)} saveDraft():void{try{localStorage.setItem(this.key(),JSON.stringify(this.draft));this.saved.set(true);setTimeout(()=>this.saved.set(false),2500)}catch{}}
  private key():string{return `brightpath-plan-year5-week-${this.week}-${this.slug}`} private loadDraft():void{try{const value=localStorage.getItem(this.key());if(value)this.draft={...this.draft,...JSON.parse(value)}}catch{}}
  private slugify(value:string):string{return value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
}
