import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { LanguageService } from '../../core/services/language.service';
import { RetrievalStarterComponent } from './retrieval-starter.component';
import { downloadFile, lessonFileUrl } from '../../shared/lesson-files';

interface CurriculumWeek { week:number; term:'Autumn'|'Spring'|'Summer'; unit:string; days:string[]; }
interface PracticeQuestion { q:string; a:string; }

@Component({
  selector:'bp-year5-maths-lesson', standalone:true, imports:[RouterLink,FormsModule,RetrievalStarterComponent], changeDetection:ChangeDetectionStrategy.OnPush,
  template:`
    @if (title()) {
      <header class="bp-page-hero"><div class="bp-container"><a class="back" [routerLink]="l('/curriculum/maths/year/5')">← Year 5 curriculum map</a><span class="bp-chip">Year 5 Maths · {{ term() }} · Week {{ week }} · Day {{ day() }}</span><h1>{{ title() }}</h1><p>Develop secure Year 5 understanding through representation, fluency, reasoning and application.</p></div></header>
      <main class="bp-section"><div class="bp-container lesson-layout">
        <section class="powerpoint bp-card" style="grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:1.5rem;padding:1.4rem 1.6rem;border-left:7px solid var(--accent-sky)"><div><span class="bp-label">Teaching resource</span><h2 style="margin:.3rem 0">Year 5 teaching PowerPoint</h2><p style="margin:0;color:var(--text-muted)">12 editable slides with retrieval, vocabulary, pre-teach, modelling, guided and independent practice, challenge, answers and review.</p></div><a class="bp-btn" style="white-space:nowrap" [href]="powerpointUrl()" (click)="$event.preventDefault(); downloadFile(powerpointUrl())">Download PowerPoint</a></section>
        <section class="plan bp-card"><div class="section-head"><div><span class="bp-label">Teacher planning</span><h2>Lesson focus and preparation</h2></div><button class="bp-btn" type="button" (click)="saveDraft()">Save notes</button></div><p class="hint">Use these notes to adapt the lesson for your class.</p><div class="field-grid"><label>Teacher / class<input [(ngModel)]="draft.teacher" /></label><label>Date<input type="date" [(ngModel)]="draft.date" /></label></div><label>Pre-teach, SEND and EAL support<textarea rows="3" [(ngModel)]="draft.support"></textarea></label><label>Assessment notes and next steps<textarea rows="4" [(ngModel)]="draft.assessment"></textarea></label>@if(saved()){<p class="saved">✓ Saved on this device</p>}</section>
        <aside class="overview bp-card"><span class="bp-label">Teaching point</span><h2>{{ unit() }}</h2><p>{{ teachingPoint() }}</p><h3>Key vocabulary</h3><p>{{ vocabulary() }}</p><h3>Watch for</h3><p>Pupils applying a remembered rule without checking whether it fits the representation or context.</p></aside>
        <bp-retrieval-starter [year]="5" [week]="week" [day]="day()" />
        <section class="sequence"><span class="bp-label">60-minute teaching sequence</span><h2>Lesson at a glance</h2><div class="sequence-grid"><article class="bp-card"><b>1 · Revisit</b><p>Complete the five retrieval questions and discuss efficient strategies.</p><small>5 minutes</small></article><article class="bp-card"><b>2 · Model</b><p>Represent {{ unit().toLowerCase() }} clearly. Think aloud, connect each step and model one common error.</p><small>15 minutes</small></article><article class="bp-card"><b>3 · Guided practice</b><p>Solve examples together. Ask pupils to justify choices using the model and precise vocabulary.</p><small>15 minutes</small></article><article class="bp-card"><b>4 · Independent</b><p>Move from fluency to reasoning and one contextual problem. Check methods, not only answers.</p><small>20 minutes</small></article><article class="bp-card"><b>5 · Review</b><p>Compare two strategies and complete one exit question linked to the lesson focus.</p><small>5 minutes</small></article></div></section>
        <section class="practice"><div class="section-head"><div><span class="bp-label">Differentiated practice</span><h2>Lesson-specific pupil questions</h2></div><button class="answer-button" type="button" (click)="showAnswers.update(value=>!value)">{{ showAnswers()?'Hide answers':'Show answers' }}</button></div><div class="level-tabs" role="tablist"><button type="button" [class.active]="level()==='lower'" (click)="level.set('lower')">Lower support</button><button type="button" [class.active]="level()==='expected'" (click)="level.set('expected')">Expected</button><button type="button" [class.active]="level()==='higher'" (click)="level.set('higher')">Higher challenge</button></div><ol class="question-list">@for(item of questions();track item.q){<li><span>{{ item.q }}</span>@if(showAnswers()){<b>{{ item.a }}</b>}</li>}</ol><p class="practice-note">Lower uses smaller numbers and prompts. Expected matches the Year 5 objective. Higher requires explanation, proof or more than one step.</p></section>
        <aside class="preteach bp-card"><div><span class="bp-label">Before the lesson</span><h2>Pre-teach focus</h2><p>Revisit the vocabulary and prerequisite fact pupils need for {{ unit().toLowerCase() }}.</p></div><ul><li>✓ Use one clear representation</li><li>✓ Rehearse a complete spoken sentence</li><li>✓ Check one example independently</li></ul></aside>
      </div></main>
    } @else {<div class="bp-loading"><span class="bp-spinner"></span>Loading Year 5 lesson…</div>}
  `,
  styles:[`.back{display:block;width:max-content;margin-bottom:1rem;font-weight:700}.lesson-layout{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(320px,.95fr);gap:1.5rem}.plan,.overview,.preteach{padding:clamp(1.2rem,3vw,2rem)}.section-head{display:flex;align-items:start;justify-content:space-between;gap:1rem}.section-head h2,.overview h2{margin:.3rem 0}.hint,.overview p{color:var(--text-muted)}label{display:block;margin-top:.85rem;font-size:.82rem;font-weight:750}label input,label textarea{margin-top:.3rem;font-weight:400}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.saved{color:var(--accent-emerald);font-weight:800}.overview{border-top:6px solid var(--accent-sky)}.overview h3{margin:1rem 0 .2rem;font-size:.9rem}.sequence,.practice,.preteach{grid-column:1/-1}.sequence h2,.practice h2{margin:.35rem 0 1rem}.sequence-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.8rem}.sequence-grid article{display:flex;flex-direction:column;padding:1rem}.sequence-grid p{flex:1;color:var(--slate-600);font-size:.88rem}.sequence-grid small{color:var(--brand-d);font-weight:800}.preteach{display:grid;grid-template-columns:1fr 1fr;gap:2rem;background:linear-gradient(135deg,var(--brand-tint),var(--white))}.preteach li{margin:.45rem 0}@media(max-width:950px){.lesson-layout,.sequence-grid{grid-template-columns:1fr}.plan,.overview,.sequence,.practice,.preteach{grid-column:1}}@media(max-width:560px){.field-grid,.preteach{grid-template-columns:1fr}.section-head{display:block}.section-head .bp-btn{margin-top:.6rem;width:100%;justify-content:center}}`,`.practice{padding:clamp(1.2rem,3vw,2rem);border-radius:var(--r-md);background:var(--white);box-shadow:var(--shadow-sm)}.answer-button,.level-tabs button{border:1px solid var(--border);border-radius:999px;padding:.6rem .9rem;background:var(--white);color:var(--brand-d);font:750 .82rem var(--font-body);cursor:pointer}.level-tabs{display:flex;flex-wrap:wrap;gap:.55rem;margin:1rem 0}.level-tabs button.active{border-color:var(--brand-d);background:var(--brand-d);color:var(--white)}.question-list{display:grid;grid-template-columns:repeat(2,1fr);gap:.75rem;margin:0;padding:0;list-style:none;counter-reset:q}.question-list li{counter-increment:q;min-height:95px;padding:1rem;border:1px solid var(--border);border-left:5px solid var(--accent-sky);border-radius:12px;background:var(--page-bg);font-weight:700}.question-list li::before{content:counter(q);display:inline-grid;place-items:center;width:1.5rem;height:1.5rem;margin-right:.5rem;border-radius:50%;background:var(--brand-d);color:var(--white);font-size:.72rem}.question-list b{display:block;margin:.7rem 0 0 2.1rem;color:var(--accent-emerald)}.practice-note{margin:.9rem 0 0;color:var(--text-muted);font-size:.82rem}@media(max-width:650px){.question-list{grid-template-columns:1fr}}`]
})
export class Year5MathsLessonComponent {
  readonly downloadFile=downloadFile;
  private http=inject(HttpClient); private route=inject(ActivatedRoute); private lang=inject(LanguageService);
  readonly week=Number((this.route.snapshot.paramMap.get('week')??'week-1').replace('week-','')); readonly slug=this.route.snapshot.paramMap.get('slug')??''; readonly plan=signal<CurriculumWeek[]>([]); readonly saved=signal(false); readonly showAnswers=signal(false); readonly level=signal<'lower'|'expected'|'higher'>('expected');
  readonly weekData=computed(()=>this.plan().find(item=>item.week===this.week)); readonly day=computed(()=>Math.max(1,(this.weekData()?.days.findIndex(item=>this.slugify(item)===this.slug)??0)+1)); readonly title=computed(()=>this.weekData()?.days[this.day()-1]??''); readonly unit=computed(()=>this.weekData()?.unit??'Year 5 mathematics'); readonly term=computed(()=>this.weekData()?.term??(this.week<=10?'Autumn':this.week<=20?'Spring':'Summer'));
  readonly teachingPoint=computed(()=>{const lead=this.title().split(':')[0];return `${lead}: connect the mathematical structure to an efficient method, then explain why the method works.`}); readonly vocabulary=computed(()=>this.vocabularyFor(this.unit()).join(' · '));
  readonly questions=computed(()=>this.makeQuestions(this.level()));
  draft={teacher:'',date:'',support:'',assessment:''};
  constructor(){this.http.get<CurriculumWeek[]>('/curriculum-plans/maths/year-5.json').subscribe(items=>{this.plan.set(items);this.loadDraft()})}
  l(path:string):string{return this.lang.localise(path)} saveDraft():void{try{localStorage.setItem(this.key(),JSON.stringify(this.draft));this.saved.set(true);setTimeout(()=>this.saved.set(false),2500)}catch{}}
  powerpointUrl():string{return lessonFileUrl(`year-5-maths/week-${this.week}/${this.slug}/interactive-teaching-slides.pptx`)}
  private key():string{return `brightpath-plan-year5-week-${this.week}-${this.slug}`} private loadDraft():void{try{const value=localStorage.getItem(this.key());if(value)this.draft={...this.draft,...JSON.parse(value)}}catch{}}
  private slugify(value:string):string{return value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  private makeQuestions(level:'lower'|'expected'|'higher'):PracticeQuestion[]{
    const hard=level==='higher',low=level==='lower',d=this.day(),s=this.week*17+d*11,n=low?100+s%80:hard?10000+s*37:1000+s*19;
    const explain=(q:string)=>hard?`${q} Explain or prove your answer.`:q;
    const list=(factory:(i:number)=>PracticeQuestion)=>Array.from({length:5},(_,i)=>factory(i));
    if(this.week===1)return list(i=>{const x=n+i*1111;return{q:explain(`What is the value of ${String(x)[Math.min(2,i%String(x).length)]} in ${x.toLocaleString()}?`),a:`Use its place in ${x.toLocaleString()} to state the value.`}});
    if(this.week===2)return list(i=>{const x=(i+2)*10**(low?2:hard?5:4);return{q:explain(`${x.toLocaleString()} ÷ 10 = ?`),a:(x/10).toLocaleString()}});
    if(this.week===3)return list(i=>{const x=n+i*137,place=low?10:hard?10000:1000;return{q:explain(`Round ${x.toLocaleString()} to the nearest ${place.toLocaleString()}.`),a:(Math.round(x/place)*place).toLocaleString()}});
    if(this.week===4)return list(i=>{const a=n+i*143,b=(low?80:hard?4827:827)+i*39,op=i%2?'-':'+';return{q:explain(`Calculate ${a.toLocaleString()} ${op} ${b.toLocaleString()}.`),a:(op==='+'?a+b:a-b).toLocaleString()}});
    if(this.week===5)return list(i=>{const a=(low?23:hard?2345:345)+i*7,b=2+(i+d)%8;return{q:explain(`${a} × ${b} =`),a:String(a*b)}});
    if(this.week===6)return list(i=>{const divisor=2+(i+d)%7,quot=(low?12:hard?1203:123)+i*9,total=divisor*quot;return{q:explain(`${total.toLocaleString()} ÷ ${divisor} =`),a:quot.toLocaleString()}});
    if(this.week===7)return list(i=>{const x=[24,36,48,60,72][i]+(hard?12:0);return{q:explain(`Write all the factor pairs of ${x}.`),a:this.factorPairs(x)}});
    if(this.week===8)return list(i=>{const x=2+i;return{q:explain(`Calculate ${x}³ + ${i+1}².`),a:String(x**3+(i+1)**2)}});
    if(this.week===9)return list(i=>{const x=(low?3.4:hard?0.347:34.7)+i*.1,m=[10,100,1000][i%3];return{q:explain(`${Number(x.toFixed(3))} × ${m} =`),a:String(Number((x*m).toFixed(3)))}});
    if(this.week>=11&&this.week<=14)return list(i=>{const den=low?8:12,num=1+(i+d)%5,other=1+(i*2)%5;if(this.week===14)return{q:explain(`${num}/${den} × ${2+i} =`),a:`${num*(2+i)}/${den}`};return{q:explain(`${num}/${den} + ${other}/${den} =`),a:`${num+other}/${den}`}});
    if(this.week===15||this.week===16)return list(i=>{const x=Number(((low?1.2:hard?12.345:3.456)+i*.137).toFixed(3));return{q:explain(this.week===16?`Round ${x} to 2 decimal places.`:`What is the value of the digit 5 in ${x}?`),a:this.week===16?x.toFixed(2):'Use the tenths, hundredths and thousandths places.'}});
    if(this.week===17)return list(i=>{const pct=[10,20,25,50,75][i],total=(low?40:hard?360:120)+i*20;return{q:explain(`Find ${pct}% of ${total}.`),a:String(total*pct/100)}});
    if(this.week===18||this.week===19)return list(i=>{const pct=[10,20,25,50,75][i],decimal=pct/100;return{q:explain(`Write ${pct}% as a decimal and a fraction.`),a:`${decimal} and ${pct}/100`}});
    if(this.week===21)return list(i=>{const km=(low?2:hard?3.75:2.5)+i*.25;return{q:explain(`Convert ${km} km to metres.`),a:`${km*1000} m`}});
    if(this.week===22)return list(i=>{const a=(low?4:hard?14:8)+i,b=3+(i%4);return{q:explain(`A rectangle is ${a} cm by ${b} cm. Find its perimeter and area.`),a:`Perimeter ${2*(a+b)} cm; area ${a*b} cm²`}});
    if(this.week===23)return list(i=>{const a=2+i,b=3+(i%3),c=4+(i%2);return{q:explain(`Find the volume of a cuboid ${a} cm × ${b} cm × ${c} cm.`),a:`${a*b*c} cm³`}});
    if(this.week===24)return list(i=>{const a=35+i*10,b=90+i*5;return{q:explain(`Angles on a straight line are ${a}° and ${b}°. Find the missing angle.`),a:`${180-a-b}°`}});
    if(this.week===25)return list(i=>({q:explain(`Name a quadrilateral with ${i%2?'one pair':'two pairs'} of parallel sides and state another property.`),a:i%2?'Trapezium; accept a correct property.':'Parallelogram, rectangle, rhombus or square; accept a correct property.'}));
    if(this.week===26)return list(i=>{const x=1+i,y=2+(i%3),dx=2+(d%2),dy=1+(i%2);return{q:explain(`Translate (${x}, ${y}) ${dx} right and ${dy} up.`),a:`(${x+dx}, ${y+dy})`}});
    if(this.week===27)return list(i=>{const values=[12+i,18+i*2,15+i,21+i,24+i];return{q:explain(`The values are ${values.join(', ')}. Find the total and the difference between the greatest and least.`),a:`Total ${values.reduce((a,b)=>a+b,0)}; difference ${Math.max(...values)-Math.min(...values)}`}});
    if(this.week===28)return list(i=>{const price=(125+i*37)/100,count=2+i;return{q:explain(`${count} items cost £${price.toFixed(2)} each. Find the total.`),a:`£${(price*count).toFixed(2)}`}});
    if(this.week===29)return list(i=>{const x=3+i;return{q:explain(`Investigate: is ${x}² + ${x+1}² always odd? Test and explain.`),a:`${x*x+(x+1)*(x+1)}; consecutive squares have opposite parity, so the sum is odd.`}});
    return list(i=>{const a=(low?120:hard?12000:1200)+s+i*47,b=3+i;return{q:explain(`Calculate ${a.toLocaleString()} ÷ ${b}, then check by multiplication.`),a:`${a%b===0?a/b:`${Math.floor(a/b)} r ${a%b}`}`}});
  }
  private factorPairs(value:number):string{const pairs:string[]=[];for(let i=1;i<=Math.sqrt(value);i++)if(value%i===0)pairs.push(`${i} × ${value/i}`);return pairs.join(', ')}
  private vocabularyFor(unit:string):string[]{const u=unit.toLowerCase();if(u.includes('fraction'))return['numerator','denominator','equivalent','improper fraction','mixed number'];if(u.includes('decimal')||u.includes('percent'))return['decimal place','thousandth','percent','equivalent','round'];if(u.includes('multiply')||u.includes('factor')||u.includes('square'))return['factor','multiple','product','prime','composite'];if(u.includes('division'))return['dividend','divisor','quotient','remainder','inverse'];if(u.includes('measurement')||u.includes('perimeter')||u.includes('volume'))return['convert','unit','perimeter','area','volume'];if(u.includes('geometry'))return['angle','parallel','coordinate','translate','reflect'];if(u.includes('statistics'))return['axis','scale','interval','data','difference'];if(u.includes('financial'))return['pounds','pence','total','change','estimate'];return['place value','digit','partition','round','compare']}
}
